{
  "hash": "894003e39aecb47a4af59626aaa476c9",
  "result": {
    "engine": "jupyter",
    "markdown": "# Motivating Datasets {#sec-datasets}\n\n> \"*The purpose of computing is insight, not numbers.*\" --- Richard Hamming\n\nThis chapter previews the datasets and test functions that serve as running examples throughout the book. We present them here so that later chapters can focus on methodology rather than data description. @tbl-datasets-overview provides a summary; the \"Chapter\" column indicates where each dataset is first analyzed in depth.\n\n| Dataset | $d$ | $n$ | Type | Challenge | Chapter |\n|:--------|----:|----:|:-----|:----------|:--------|\n| Motorcycle | 1 | 133 | Real | Heteroscedastic noise | @sec-iqn |\n| Phantom | 2 | 9k | Synthetic | Sinusoidal jump boundary | @sec-jumps |\n| Star | 2 | 9k | Synthetic | Star-shaped jump boundary | @sec-jumps |\n| AMHV | 4 | 8.5k | Simulator | Smooth regime transition | @sec-jumps |\n| BGP (2D--4D) | 2--4 | 2k | Synthetic (GP) | Piecewise-continuous | @sec-surrogates |\n| Friedman 10D | 10 | 2k--20k | Synthetic | Inert variables, interactions | @sec-surrogates |\n| Michalewicz 4D | 4 | 90k | Synthetic | Large $n$, MJGP infeasible | @sec-jumps |\n| 2D Exponential | 2 | 100 | Synthetic | Smooth, small $n$ | @sec-active-learning |\n| Rocket LGBB | 3 | 300 | Simulator | Sound-barrier ridge | @sec-active-learning |\n| Satellite GRACE | 7 | 500 | Simulator | Smooth, high $d$ | @sec-active-learning |\n| Lake Temperature | 6 | 282k | Real | High SNR, temporal | @sec-calibration |\n| Ebola ABM | 5 | 300 | Simulator | Bimodal, no likelihood | @sec-bayesian-inference |\n| LaLonde | 8 | 445 | Real | Causal inference | @sec-causal |\n\n: Datasets used throughout this book. Dimension $d$ is the number of input features; $n$ is the typical sample size used in our experiments. {#tbl-datasets-overview tbl-colwidths=\"[20,5,8,14,30,23]\"}\n\nThe datasets span heteroscedasticity, jump discontinuities, high dimensionality, scalability, active learning, likelihood-free inference, and causal estimation. Some are synthetic (allowing exact metrics against the truth), some come from real scientific applications, and some involve expensive simulators. A recurring theme is the tension between GP-based methods (calibrated uncertainty from small samples, but $\\mathcal{O}(n^3)$ cost and smoothness assumptions) and GBC (scalable, flexible, but requiring more data to learn structure that a good kernel encodes for free).\n\n\n## Motorcycle Crash Data {#sec-data-motorcycle}\n\nThe *motorcycle crash dataset* [@silverman1985some] records head acceleration ($g$) versus time (ms) for $n = 133$ simulated motorcycle crashes. It is the canonical benchmark for heteroscedastic regression: variance changes by roughly two orders of magnitude across the input range, from quiet pre-impact measurements to violent crash-event deceleration.\n\n::: {.callout-note}\n## Dataset summary\n- *Source*: @silverman1985some; available in R's `MASS::mcycle`\n- *Size*: $n = 133$ observations, $d = 1$ input (time after impact)\n- *Response*: Head acceleration ($g$)\n- *Key feature*: Variance changes dramatically across the input range\n- *Used in*: @sec-iqn-motorcycle (IQN quantile fan), @sec-surrogates (GBC vs. hetGP)\n:::\n\n::: {.cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nfrom gbc.data import load_motorcycle\n\nX_moto, y_moto = load_motorcycle()\nt = X_moto.ravel()\n\nfig, ax = plt.subplots(1, 1, figsize=(7, 3.5))\nax.scatter(t, y_moto, s=12, alpha=0.6, color='k', zorder=3)\nax.axvspan(15, 35, alpha=0.08, color='red', label='High-variance region')\nax.set_xlabel(\"Time after impact (ms)\")\nax.set_ylabel(\"Head acceleration ($g$)\")\nax.set_title(\"Motorcycle crash data (Silverman, 1985)\")\nax.legend(fontsize=8)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Motorcycle crash data: head acceleration versus time after impact. The shaded region highlights the high-variance crash event.](ch02-datasets_files/figure-pdf/fig-data-motorcycle-output-1.pdf){#fig-data-motorcycle fig-pos='H'}\n:::\n:::\n\n\nOn this benchmark, GBC and the purpose-built heteroscedastic GP (`hetGP`) achieve comparable CRPS ($\\approx 12.5$), but the motorcycle data has only 133 observations --- a regime where GPs are at their best. The real advantage of GBC emerges on larger, higher-dimensional problems.\n\n\n## Flowers Test Functions {#sec-data-flowers}\n\nThe Flowers benchmark suite [@flowers2026modular] consists of four synthetic datasets designed to test surrogate methods on response surfaces with *jump discontinuities*. Jump discontinuities arise whenever a physical system undergoes a regime change --- a material fractures, an epidemic tips from containment to exponential growth, or a manufacturing line hits capacity. The suite isolates this challenge in controlled settings where the true boundary geometry is known exactly.\n\n### Phantom Function {#sec-data-phantom}\n\nA bivariate response surface ($d = 2$) with a *sinusoidal jump boundary* at $\\sin(x_1) = x_2$. Each regime generates the response from a different Gaussian component.\n\n::: {.callout-note}\n## Dataset summary\n- *Source*: @flowers2026modular\n- *Size*: $N = 10{,}201$ on a grid; $n_{\\text{train}} \\approx 9{,}000$ after 90/10 split\n- *Dimension*: $d = 2$\n- *Response*: Bimodal (two Gaussian components separated by jump)\n- *Boundary*: $\\sin(x_1) = x_2$ (sinusoidal)\n- *Used in*: @sec-jumps-phantom (Aug-IQN benchmark)\n:::\n\n::: {.cell execution_count=2}\n``` {.python .cell-code code-fold=\"true\"}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nnp.random.seed(42)\nn = 5000\nx1 = np.random.uniform(-3, 3, n)\nx2 = np.random.uniform(-3, 3, n)\n\nregime = (x2 > np.sin(x1)).astype(int)\ny = np.where(regime == 0,\n             np.random.normal(2.0, 0.5, n),\n             np.random.normal(8.0, 0.5, n))\n\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n\nsc = ax1.scatter(x1, x2, c=y, s=2, alpha=0.5, cmap='RdYlBu_r', rasterized=True)\nxg = np.linspace(-3, 3, 200)\nax1.plot(xg, np.sin(xg), 'k--', linewidth=1.5, label=r'$\\sin(x_1) = x_2$')\nax1.set_xlabel(\"$x_1$\")\nax1.set_ylabel(\"$x_2$\")\nax1.set_title(\"Phantom: response surface\")\nax1.legend(fontsize=8, loc='upper right')\nplt.colorbar(sc, ax=ax1, label='Response')\n\nax2.hist(y[regime == 0], bins=40, alpha=0.6, color='steelblue',\n         label='Regime 0', density=True)\nax2.hist(y[regime == 1], bins=40, alpha=0.6, color='coral',\n         label='Regime 1', density=True)\nax2.set_xlabel(\"Response $y$\")\nax2.set_ylabel(\"Density\")\nax2.set_title(\"Phantom: bimodal marginal\")\nax2.legend(fontsize=8)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Phantom function: the response jumps across the sinusoidal boundary $\\sin(x_1) = x_2$. Left: response surface colored by value. Right: the bimodal marginal distribution of the response.](ch02-datasets_files/figure-pdf/fig-data-phantom-output-1.pdf){#fig-data-phantom fig-pos='H'}\n:::\n:::\n\n\nGBC-Aug slightly outperforms MJGP on CRPS (0.009 vs. 0.010) while improving RMSE by 17% (0.044 vs. 0.053), training in ~23 seconds per replicate on GPU versus over 600 seconds for MJGP on CPU.\n\n### Star Function {#sec-data-star}\n\nA bivariate response ($d = 2$) with an angular, *star-shaped partition*. The boundary has sharp corners at each of five tips where the two regimes nearly touch, making boundary detection harder than Phantom.\n\n::: {.callout-note}\n## Dataset summary\n- *Source*: @flowers2026modular\n- *Size*: $N = 10{,}201$; $n_{\\text{train}} \\approx 9{,}000$ after 90/10 split\n- *Dimension*: $d = 2$\n- *Response*: Bimodal (same structure as Phantom)\n- *Boundary*: Star-shaped polygon with sharp corners\n- *Used in*: @sec-jumps-star (Aug-IQN benchmark)\n:::\n\n::: {.cell execution_count=3}\n``` {.python .cell-code code-fold=\"true\"}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nnp.random.seed(42)\nn = 5000\nx1 = np.random.uniform(-1.5, 1.5, n)\nx2 = np.random.uniform(-1.5, 1.5, n)\n\ntheta = np.arctan2(x2, x1)\nr = np.sqrt(x1**2 + x2**2)\nr_star = 0.4 + 0.6 * (0.5 + 0.5 * np.cos(5 * theta))\nregime = (r < r_star).astype(int)\n\ny = np.where(regime == 1,\n             np.random.normal(7.0, 0.5, n),\n             np.random.normal(2.0, 0.5, n))\n\nfig, ax = plt.subplots(1, 1, figsize=(5.5, 5))\nsc = ax.scatter(x1, x2, c=y, s=2, alpha=0.5, cmap='RdYlBu_r', rasterized=True)\ntheta_plot = np.linspace(-np.pi, np.pi, 500)\nr_plot = 0.4 + 0.6 * (0.5 + 0.5 * np.cos(5 * theta_plot))\nax.plot(r_plot * np.cos(theta_plot), r_plot * np.sin(theta_plot),\n        'k--', linewidth=1.5, label='Star boundary')\nax.set_xlabel(\"$x_1$\")\nax.set_ylabel(\"$x_2$\")\nax.set_title(\"Star: response surface\")\nax.legend(fontsize=8)\nax.set_aspect('equal')\nplt.colorbar(sc, ax=ax, label='Response', shrink=0.8)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Star function: the response jumps across a star-shaped boundary. Points inside the star belong to one regime; points outside belong to another.](ch02-datasets_files/figure-pdf/fig-data-star-output-1.pdf){#fig-data-star fig-pos='H'}\n:::\n:::\n\n\nGBC-Aug achieves CRPS = 0.013, outperforming MJGP's 0.024 by 46% --- the largest improvement in our jump-boundary comparisons.\n\n### AMHV Function {#sec-data-amhv}\n\nThe AMHV (Automated Material Handling Vehicle) dataset [@kang2024bayesian] records average transport time for autonomous vehicles in a semiconductor fab. Unlike Phantom and Star, the response is *not cleanly bimodal* --- the regime transition is gradual, making this a control case where augmentation is unnecessary and plain GBC suffices.\n\n::: {.callout-note}\n## Dataset summary\n- *Source*: @kang2024bayesian\n- *Size*: $N = 9{,}503$, $d = 4$\n- *Inputs*: Vehicle speed, acceleration, minimum inter-vehicle distance, empty-vehicle search range\n- *Response*: Average transport time (seconds)\n- *Key feature*: Smooth regime transition (NOT a sharp binary jump)\n- *Used in*: @sec-jumps-amhv (plain GBC vs. MJGP)\n:::\n\n### Michalewicz Function {#sec-data-michalewicz}\n\nThe Michalewicz function [@surjanovic2013virtual] is a standard optimization test function with steep ridges and valleys:\n$$\nf(x) = -\\sum_{i=1}^{d} \\sin(x_i) \\sin^{2m}\\!\\left(\\frac{i \\, x_i^2}{\\pi}\\right), \\quad x_i \\in [0, \\pi],\n$$ {#eq-michalewicz}\nwhere $m = 10$ controls the steepness. In the Flowers suite, a $0.5$ offset is added to the flat region, introducing a jump manifold in four-dimensional input space.\n\n::: {.callout-note}\n## Dataset summary\n- *Source*: @surjanovic2013virtual (Virtual Library of Simulation Experiments)\n- *Size*: $N = 100{,}000$ (Latin hypercube sample), $d = 4$\n- *Key feature*: Large $n$ makes MJGP computationally infeasible ($\\geq 48$ hours)\n- *Used in*: @sec-jumps (scalability demonstration)\n:::\n\nWith $n = 90{,}000$ training points, the GP's $\\mathcal{O}(n^3)$ cost is infeasible ($\\approx 65$ GB for the covariance matrix alone). GBC trains in under 30 minutes on a single GPU, achieving CRPS = 0.031 with 91% coverage.\n\n\n## BGP Test Functions {#sec-data-bgp}\n\nThe Bi-mixture Gaussian Process (BGP) test problems from @park2026active provide controlled *piecewise-continuous* response surfaces. A random hyperplane $a^\\top x = 0$ partitions the unit hypercube into two regions, each with an independent GP realization at different mean levels:\n$$\nf_1 \\sim \\mathcal{GP}(13,\\; 9\\, k_{\\text{SE}}), \\quad f_2 \\sim \\mathcal{GP}(0,\\; 9\\, k_{\\text{SE}}),\n$$ {#eq-bgp-dgp}\nwith $k_{\\text{SE}}$ using length scale $\\ell = 0.1d$ and additive noise $\\varepsilon \\sim \\mathcal{N}(0, 4)$.\n\n::: {.callout-note}\n## Dataset summary\n- *Source*: @park2026active\n- *Size*: $N = 2{,}000$ per realization, $d \\in \\{2, 3, 4\\}$\n- *Response*: Piecewise-continuous (two GP realizations with different means)\n- *Partition*: Random hyperplane $a^\\top x = 0$ with $a \\in \\{-1, +1\\}^d$\n- *Used in*: @sec-surr-bgp (GBC vs. stationary GP)\n:::\n\n::: {.cell execution_count=4}\n``` {.python .cell-code code-fold=\"true\"}\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom scipy.linalg import cholesky\n\nnp.random.seed(7)\nn = 800\nd = 2\nX = np.random.uniform(-0.5, 0.5, size=(n, d))\n\na = np.array([1.0, -1.0])\nregion = (X @ a >= 0).astype(int)\n\ndef se_kernel(X1, X2, sigma2=9.0, ls=0.2):\n    diff = X1[:, np.newaxis, :] - X2[np.newaxis, :, :]\n    sq_dist = np.sum(diff**2, axis=-1)\n    return sigma2 * np.exp(-sq_dist / (2.0 * ls**2))\n\nf = np.zeros(n)\nfor idx_set, mean_val in [(region == 1, 13.0), (region == 0, 0.0)]:\n    idx = np.where(idx_set)[0]\n    if len(idx) == 0:\n        continue\n    K = se_kernel(X[idx], X[idx]) + 1e-5 * np.eye(len(idx))\n    L = cholesky(K, lower=True)\n    f[idx] = L @ np.random.randn(len(idx)) + mean_val\n\ny = f + np.random.normal(0, 2, n)\n\nfig, ax = plt.subplots(1, 1, figsize=(5.5, 5))\nsc = ax.scatter(X[:, 0], X[:, 1], c=y, s=8, alpha=0.6, cmap='RdYlBu_r',\n                rasterized=True)\nxb = np.linspace(-0.5, 0.5, 100)\nax.plot(xb, xb, 'k--', linewidth=1.5, label=r'$a^\\top x = 0$')\nax.set_xlabel(\"$x_1$\")\nax.set_ylabel(\"$x_2$\")\nax.set_xlim(-0.55, 0.55)\nax.set_ylim(-0.55, 0.55)\nax.set_title(\"BGP realization ($d = 2$)\")\nax.legend(fontsize=8)\nax.set_aspect('equal')\nplt.colorbar(sc, ax=ax, label='Response', shrink=0.8)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![One realization of the BGP test function in $d = 2$ with $a = (1, -1)$. The dashed line shows the partition boundary $a^\\top x = 0$ (i.e., $x_1 = x_2$). The two GP regimes have means 0 and 13, creating a visible jump.](ch02-datasets_files/figure-pdf/fig-data-bgp-output-1.pdf){#fig-data-bgp fig-pos='H'}\n:::\n:::\n\n\nGBC's CRPS advantage over the stationary GP grows from 11% at $d = 2$ to 26% at $d = 4$, because the GP's single global length scale becomes progressively less effective as more training data falls near the hyperplane boundary. Full results appear in @sec-surr-bgp.\n\n\n## Friedman 10D {#sec-data-friedman}\n\nThe Friedman function [@friedman1991multivariate] is a standard benchmark for high-dimensional regression:\n$$\nf(x) = 10\\sin(\\pi x_1 x_2) + 20(x_3 - 0.5)^2 + 10 x_4 + 5 x_5, \\quad x \\in [0,1]^{10}.\n$$ {#eq-friedman}\n\nOnly five of the ten inputs are active; the remaining five are inert noise variables. The $\\sin(\\pi x_1 x_2)$ term creates a non-separable interaction that separable GP kernels cannot represent faithfully.\n\n::: {.callout-note}\n## Dataset summary\n- *Source*: @friedman1991multivariate\n- *Size*: $n \\in \\{500, \\ldots, 20{,}000\\}$ (varies by experiment), $d = 10$\n- *Active inputs*: Only $x_1, \\ldots, x_5$; the remaining five are inert noise variables\n- *Key features*: Nonlinear interaction ($\\sin(\\pi x_1 x_2)$), quadratic and linear terms, inert variables\n- *Noise*: $\\varepsilon \\sim \\mathcal{N}(0, 1)$\n- *Used in*: @sec-surr-friedman (GBC vs. GP), @sec-surr-scaling (scaling study)\n:::\n\n::: {.cell execution_count=5}\n``` {.python .cell-code code-fold=\"true\"}\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom gbc.data import friedman1\n\nn_grid = 80\nx1g = np.linspace(0, 1, n_grid)\nx2g = np.linspace(0, 1, n_grid)\nX1, X2 = np.meshgrid(x1g, x2g)\nX_grid = np.column_stack([X1.ravel(), X2.ravel(),\n                          0.5 * np.ones(n_grid**2),\n                          0.5 * np.ones(n_grid**2),\n                          0.5 * np.ones(n_grid**2),\n                          0.5 * np.ones(n_grid**2),\n                          0.5 * np.ones(n_grid**2),\n                          0.5 * np.ones(n_grid**2),\n                          0.5 * np.ones(n_grid**2),\n                          0.5 * np.ones(n_grid**2)])\nY_grid = friedman1(X_grid).reshape(n_grid, n_grid)\n\nfig, ax = plt.subplots(1, 1, figsize=(6, 5))\ncf = ax.contourf(X1, X2, Y_grid, levels=20, cmap='viridis')\nax.set_xlabel(\"$x_1$\")\nax.set_ylabel(\"$x_2$\")\nax.set_title(\"Friedman function: $f(x_1, x_2, 0.5, 0.5, 0.5, 0, \\\\ldots, 0)$\")\nplt.colorbar(cf, ax=ax, label='$f(x)$')\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Friedman function: response versus the two interacting inputs $x_1$ and $x_2$, with all other inputs at their midpoint. The sinusoidal interaction creates a complex surface that is difficult for separable GP kernels.](ch02-datasets_files/figure-pdf/fig-data-friedman-output-1.pdf){#fig-data-friedman fig-pos='H'}\n:::\n:::\n\n\nEven on this GP-friendly benchmark, GBC achieves 12% lower RMSE and 14% lower CRPS, because the multiplicative interaction between $x_1$ and $x_2$ is difficult for separable kernel functions. The GP becomes computationally infeasible beyond $n \\approx 2{,}000$ due to its $\\mathcal{O}(n^3)$ Cholesky cost; we develop this scaling comparison fully in @sec-surr-scaling.\n\n\n## Active Learning Benchmarks {#sec-data-active-learning}\n\nThe next three datasets are used in @sec-active-learning, where training points are acquired sequentially based on where the surrogate is most uncertain. They span a range from GP-favorable to GBC-favorable.\n\n### 2D Exponential {#sec-data-2dexp}\n\nThe 2D Exponential function [@sauer2023active] is a smooth, unimodal surface:\n$$\nf(x_1, x_2) = 10 \\, x_1 \\exp(-x_1^2 - x_2^2), \\quad (x_1, x_2) \\in [-2, 2]^2,\n$$ {#eq-data-2d-exp}\nwith additive Gaussian noise $\\varepsilon \\sim \\mathcal{N}(0, 0.1^2)$. This is a control case where the GP's smoothness prior is perfectly matched to the target. The GP-based DGP+ALC method achieves 21% lower RMSE than GBC-AL --- an honest assessment of GBC's limitations on small, smooth problems.\n\n::: {.callout-note}\n## Dataset summary\n- *Source*: @sauer2023active\n- *Size*: $n_0 = 10$ initial points, growing to $n = 100$ via active learning\n- *Dimension*: $d = 2$\n- *Key feature*: Smooth, unimodal --- ideal for GP surrogates\n- *Used in*: @sec-al-2d (active learning benchmark where GP wins)\n:::\n\n::: {.cell execution_count=6}\n``` {.python .cell-code code-fold=\"true\"}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nn_grid = 80\nx1g = np.linspace(-2, 2, n_grid)\nx2g = np.linspace(-2, 2, n_grid)\nX1, X2 = np.meshgrid(x1g, x2g)\nY = 10 * X1 * np.exp(-X1**2 - X2**2)\n\nfig, ax = plt.subplots(1, 1, figsize=(6, 5))\ncf = ax.contourf(X1, X2, Y, levels=20, cmap='RdYlBu_r')\nax.set_xlabel(\"$x_1$\")\nax.set_ylabel(\"$x_2$\")\nax.set_title(\"2D Exponential: $f(x_1, x_2) = 10 x_1 \\\\exp(-x_1^2 - x_2^2)$\")\nplt.colorbar(cf, ax=ax, label='$f(x)$')\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![2D Exponential function: a smooth, unimodal surface where Gaussian process surrogates excel.](ch02-datasets_files/figure-pdf/fig-data-2dexp-output-1.pdf){#fig-data-2dexp fig-pos='H'}\n:::\n:::\n\n\n### Rocket Booster (LGBB) {#sec-data-rocket}\n\nThe Langley Glide-Back Booster benchmark [@pamadi2004aerodynamic; @gramacy2020surrogates; @sauer2023active] models aerodynamics of a reusable NASA rocket booster. The three inputs are Mach number, angle of attack, and side-slip angle; the response is the side-force coefficient. A sharp nonlinear ridge at the sound barrier (Mach $\\approx 1$) makes this hostile to stationary GPs.\n\n::: {.callout-note}\n## Dataset summary\n- *Source*: @pamadi2004aerodynamic (NASA); used in @gramacy2020surrogates and @sauer2023active\n- *Size*: $n_0 = 50$ initial points, growing to $n = 300$ via active learning\n- *Dimension*: $d = 3$ (Mach number, angle of attack, side-slip angle)\n- *Response*: Side-force coefficient\n- *Key feature*: Sharp nonlinear ridge at the sound barrier (Mach $\\approx 1$)\n- *Used in*: @sec-al-rocket (active learning benchmark where GBC dominates)\n:::\n\nGBC-AL achieves $2.95\\times$ lower RMSE than DGP+ALC --- the most dominant result in our active learning comparisons, with 90% confidence bands separating completely by $n \\approx 150$.\n\n### Satellite GRACE {#sec-data-satellite}\n\nThe Satellite GRACE benchmark [@sun2019emulating; @mehta2014modeling; @sauer2023active] uses a Test Particle Monte Carlo (TPMC) simulator to compute drag coefficients for satellites in low-Earth orbit. The seven inputs describe thermospheric conditions; the response is the satellite drag coefficient. The surface is smooth and well-matched to GP assumptions.\n\n::: {.callout-note}\n## Dataset summary\n- *Source*: @sun2019emulating; TPMC simulator for GRACE satellite\n- *Size*: $n_0 = 110$ initial points (including replicate pairs), growing to $n = 500$\n- *Dimension*: $d = 7$ (atmospheric composition, velocity, temperature variables)\n- *Response*: Satellite drag coefficient\n- *Key feature*: Smooth surface, stochastic simulator (~86 seconds per evaluation)\n- *Used in*: @sec-al-satellite (active learning crossover benchmark)\n:::\n\nThis dataset reveals a *crossover*: GBC-AL leads in the early acquisition phase ($n < 300$) but the GP-based DGP+ALC overtakes GBC at larger sample sizes ($n = 500$). The lesson: when the total acquisition budget is small (the practically relevant regime for expensive simulators), GBC provides better accuracy; when the budget is large and the surface is smooth, the GP's inductive bias eventually wins.\n\n\n## Ebola Agent-Based Model {#sec-data-ebola}\n\nThe Ebola agent-based model [@fadikar2018calibrating] simulates disease spread through a population, producing 56-week epidemic trajectories as output. Five input parameters control transmission rate, initial infections, hospital intervention timing and efficacy, and travel reduction. The ABM has no tractable likelihood --- the stochastic, agent-level interactions are far too complex for any analytical likelihood function --- making it a canonical example for likelihood-free Bayesian inference.\n\n::: {.callout-note}\n## Dataset summary\n- *Source*: @fadikar2018calibrating; RAPIDD Ebola Forecasting Challenge [@viboud2018rapidd]\n- *Size*: 300 parameter scenarios, 100 replicates each, 56-week trajectories\n- *Dimension*: $d = 5$ input parameters\n- *Response*: 56-week cumulative incidence trajectory\n- *Key feature*: Bimodal output (epidemic vs. no epidemic), no tractable likelihood\n- *Used in*: @sec-bayesian-inference (posterior inference for simulator parameters)\n:::\n\nThe ABM exhibits *bimodal behavior*: for some parameter settings the epidemic takes off; for nearby settings it sputters and dies. This tipping-point structure produces a bimodal output distribution that no Gaussian surrogate can represent faithfully. We use GBC to learn the posterior quantile function and produce credible intervals for all five parameters, including in the bimodal regime. Details in @sec-bayesian-inference.\n\n\n## Lake Temperature {#sec-data-lake}\n\nThe Falling Creek Reservoir lake temperature dataset [@holthuijzen2025synthesizing] consists of $N = 281{,}764$ records combining physics-based General Lake Model (GLM) outputs with observed water temperatures at multiple depths and forecast horizons. Six input features include day of year, depth, forecast horizon, lagged surface temperature, and the GLM ensemble mean and standard deviation.\n\n::: {.callout-note}\n## Dataset summary\n- *Source*: @holthuijzen2025synthesizing; Falling Creek Reservoir, Virginia\n- *Size*: $N = 281{,}764$ ($n_{\\text{train}} = 172{,}714$, $n_{\\text{test}} = 109{,}050$)\n- *Dimension*: $d = 6$ input features\n- *Response*: Observed water temperature (${}^\\circ$C)\n- *Key feature*: High signal-to-noise ratio causes IQN failure\n- *Train/test split*: Temporal (before / after 2022-06-11)\n- *Used in*: @sec-calibration (het-MLP ensemble + conformal calibration)\n:::\n\nThis dataset illustrates a case where the IQN *fails*: the high signal-to-noise ratio (the physics-based simulator already captures most of the variance) causes the multiplicative $\\tau$-embedding architecture to collapse all quantile levels to the conditional mean. The failure motivates the het-MLP ensemble with conformal calibration developed in @sec-calibration.\n\n\n## LaLonde Wage Data {#sec-data-lalonde}\n\nThe LaLonde dataset [@lalonde1986evaluating] evaluates the effect of the National Supported Work (NSW) job training program --- a randomized experiment with known average treatment effect (ATE $\\approx$ \\$1,500--\\$2,000 in 1978 dollars), providing rare ground truth for causal inference methods.\n\n::: {.callout-note}\n## Dataset summary\n- *Source*: @lalonde1986evaluating; refined by @dehejia1999causal\n- *Size*: $n = 445$ (185 treated, 260 control)\n- *Dimension*: $d = 8$ covariates\n- *Treatment*: NSW job training program (binary)\n- *Response*: Real earnings in 1978 (dollars)\n- *Key feature*: Randomized experiment with known ATE $\\approx$ \\$1,500--\\$2,000\n- *Used in*: @sec-causal-lalonde (causal inference benchmark)\n:::\n\nGBC estimates not only the ATE but the *quantile treatment effect* (QTE) --- how the treatment reshapes the entire outcome distribution. On the LaLonde data, the QTE profile reveals that the NSW program's primary benefit is preventing the worst outcomes, with large effects at low quantiles and smaller effects at higher quantiles. We develop this approach in @sec-causal-lalonde.\n\n\n## Exercises {#sec-data-exercises}\n\n::: {#exr-data-motorcycle}\n**Exploring the motorcycle data.**\n\nLoad the motorcycle data using `from gbc.data import load_motorcycle`.\n\n(a) Plot the data and visually identify the three phases (pre-impact, crash, recovery). At approximately what time does the crash event begin and end?\n\n(b) Compute the sample standard deviation of the response in three windows: $t < 15$ ms, $15 \\leq t \\leq 35$ ms, and $t > 35$ ms. By what factor does the variance change between the pre-impact and crash phases?\n\n(c) Fit a simple linear regression of acceleration on time. Compute the residuals and plot their absolute values versus time. Does the residual plot confirm heteroscedasticity?\n\n(d) Compute a rolling standard deviation using a window of 10 observations. Plot it versus time. Does it capture the three-phase structure?\n:::\n\n::: {#exr-data-friedman}\n**Friedman function exploration.**\n\nGenerate $n = 2{,}000$ points from the Friedman function using `from gbc.data import friedman1`.\n\n(a) Compute the correlation between each of the 10 inputs and the response $y$. Which inputs have the largest absolute correlation? Does correlation correctly identify all five active variables?\n\n(b) The $\\sin(\\pi x_1 x_2)$ interaction is invisible to univariate correlations. Compute the partial dependence of $y$ on $(x_1, x_2)$ by averaging over the remaining inputs. Plot this as a contour map. How does it compare to @fig-data-friedman?\n\n(c) Add Gaussian noise with $\\sigma = 1$ and repeat the correlation analysis. Increase $\\sigma$ from 1 to 10. At what noise level does the correlation between $x_5$ and $y$ become indistinguishable from zero at a 95% confidence level?\n:::\n\n::: {#exr-data-jump}\n**Phantom boundary difficulty.**\n\nGenerate 5,000 points from the Phantom function (two Gaussian regimes separated by $\\sin(x_1) = x_2$).\n\n(a) Fit a logistic regression classifier to predict the regime from $(x_1, x_2)$. Report accuracy on a held-out test set. Why does the linear decision boundary fail?\n\n(b) Fit a $k$-nearest-neighbors classifier with $k = 5$. Does it achieve higher accuracy? Where does $k$-NN make the most errors?\n\n(c) Train a two-layer MLP with 128 hidden units. Report accuracy and compare the learned decision boundary to the true boundary $\\sin(x_1) = x_2$.\n\n(d) For each classifier, compute accuracy specifically for test points within distance 0.1 of the true boundary. How does near-boundary accuracy compare to overall accuracy?\n:::\n\n::: {#exr-data-lake}\n**Lake temperature structure.**\n\n(a) Why is a temporal train/test split more appropriate than a random split for this dataset? What assumption of standard cross-validation would a random split violate?\n\n(b) The forecast horizon $h$ ranges from 1 to 30 days. Explain why RMSE should increase with $h$. Does this suggest a single prediction interval width is appropriate for all horizons?\n\n(c) If the GLM were a perfect forecast, what signal-to-noise ratio would the statistical model face? Explain why this would cause a quantile regression model to collapse its quantile bands.\n:::\n\n::: {#exr-data-likelihood}\n**When is the likelihood unavailable?**\n\nConsider three datasets: motorcycle, Satellite GRACE, and the Ebola ABM.\n\n(a) For the motorcycle data, write down a heteroscedastic model $y_i = f(t_i) + \\sigma(t_i)\\varepsilon_i$ with $\\varepsilon_i \\sim \\mathcal{N}(0, 1)$. Why can the likelihood be evaluated in closed form?\n\n(b) The TPMC simulator for GRACE launches thousands of virtual particles. Explain why we can *run* this simulator but cannot write down $p(C_D \\mid \\theta)$ in closed form.\n\n(c) The Ebola ABM tracks individual agents through stochastic disease transitions. Explain why the likelihood of a specific 56-week trajectory is intractable. If the simulation tracks $N_{\\text{agents}} = 10{,}000$ individuals over 56 time steps, what is the approximate dimensionality of the latent state?\n:::\n\n::: {#exr-data-cost}\n**Computational cost comparison.**\n\n(a) A GP requires $\\mathcal{O}(n^3)$ flops for training and $\\mathcal{O}(n^2)$ storage. Compute the approximate flops and memory (in GB, at 8 bytes per double) for training on the motorcycle ($n = 133$), Friedman ($n = 2{,}000$), and Michalewicz ($n = 90{,}000$) data. At which $n$ does the GP become infeasible on a 64 GB machine?\n\n(b) GBC processes data in mini-batches of size $B$ for $E$ epochs. If each forward pass costs $\\mathcal{O}(B \\cdot w^2)$ flops, what is the total cost? For the Friedman benchmark ($n = 2{,}000$, $w = 128$, $B = 256$, $E = 5{,}000$), compute the total flops and compare to the GP.\n\n(c) At test time, GP prediction costs $\\mathcal{O}(n)$ per point while GBC costs $\\mathcal{O}(w^2)$. For the Satellite GRACE benchmark ($n = 500$, $w = 128$), compute the cost ratio. How does it change at $n = 10{,}000$?\n:::\n\n",
    "supporting": [
      "ch02-datasets_files/figure-pdf"
    ],
    "filters": []
  }
}