{
  "hash": "1786e85b44431bf1c89d95e4a64049ba",
  "result": {
    "engine": "jupyter",
    "markdown": "# Causal Inference via GBC {#sec-causal}\n\n> \"*No causation without manipulation.*\" -- Paul Holland\n\nIn the preceding chapters, we developed Generative Bayesian Computation as a framework for learning conditional distributions via quantile neural networks. The noise outsourcing theorem (@sec-noise-outsourcing) guarantees that any conditional distribution can be represented as $Y = G^*(\\tau, X)$ with $\\tau \\sim \\text{Uniform}(0,1)$, and the IQN architecture (@sec-iqn) learns this map from data. We applied these ideas to surrogates (@sec-surrogates), jump detection (@sec-jumps), and Bayesian inference (@sec-bayesian-inference).\n\nThis chapter turns to *causal inference*. The question is not \"what is the distribution of $Y$ given $X$?\" but rather \"what *would* the distribution of $Y$ be if we *intervened* and set the treatment to $Z = 1$ versus $Z = 0$?\" This is a fundamentally different question, and answering it requires additional structure, the potential outcomes framework.\n\nThe GBC approach to causal inference builds on a direct observation: the conditional average treatment effect (CATE) is an integral of the conditional quantile function. Since the IQN already learns the entire conditional quantile function, we get CATE estimation *for free* as a by-product. But we get much more than the CATE. We get the full conditional distribution of outcomes under each treatment arm, which reveals how treatment reshapes the entire outcome distribution, not just its mean. This is the *quantile treatment effect* (QTE), and it answers questions that neither Double Machine Learning [@chernozhukov2018double] nor Bayesian Causal Forests [@hahn2020bayesian] can address without additional estimation.\n\nThe material in this chapter draws on @nareklishvili2026causal, which develops the GBC framework for causal inference in detail. We begin with the potential outcomes framework and the three identification assumptions, then introduce the propensity score module and the composite loss function that together form the GBC causal architecture. We establish semiparametric efficiency and compare convergence rates with Double Machine Learning. The LaLonde job training benchmark and controlled simulation studies validate the theory. We close with distributional treatment effects, a concept that goes beyond both ATE and QTE to measure the total shift between treated and control outcome distributions via the Wasserstein distance from optimal transport.\n\n## The Causal Inference Problem {#sec-causal-problem}\n\nThe potential outcomes framework, due to @splawa-neyman1990application and @rubin1974estimating, provides the mathematical language for causal inference. Consider $n$ units indexed by $i = 1, \\ldots, n$. Each unit has covariates $X_i \\in \\mathbb{R}^p$ (pre-treatment characteristics such as age, income, or health status), a binary treatment indicator $Z_i \\in \\{0, 1\\}$ (with $Z_i = 1$ meaning treated and $Z_i = 0$ meaning control), and potential outcomes $Y_i(1)$ and $Y_i(0)$ representing the outcomes that *would* occur under treatment and control, respectively.\n\nThe *individual treatment effect* for unit $i$ is\n$$\n\\tau_i = Y_i(1) - Y_i(0).\n$$ {#eq-ite}\n\nThis is the quantity we would most like to know: how much does the treatment change the outcome for this specific individual? The fundamental problem of causal inference is that we can never observe both $Y_i(1)$ and $Y_i(0)$ for the same unit. We observe only one potential outcome:\n$$\nY_i = Z_i \\cdot Y_i(1) + (1 - Z_i) \\cdot Y_i(0).\n$$ {#eq-observed}\n\nThis is the *consistency* assumption: the observed outcome equals the potential outcome under the treatment actually received. The other potential outcome is forever counterfactual, we can imagine it, but we cannot measure it.\n\n::: {.callout-note appearance=\"simple\" title=\"The Fundamental Problem of Causal Inference\"}\nFor each unit $i$, we observe either $Y_i(1)$ or $Y_i(0)$, but never both. The individual treatment effect $\\tau_i = Y_i(1) - Y_i(0)$ is therefore never directly observable. Causal inference is, at its core, a missing data problem [@holland1986statistics].\n:::\n\nTo make progress despite the missing data, we impose three assumptions.\n\n*Assumption 1: Stable Unit Treatment Value (SUTVA).* Each unit's potential outcomes depend only on its own treatment assignment, not on the treatments assigned to other units:\n$$\nY_i = Y_i(Z_i), \\quad \\text{not } Y_i(Z_1, \\ldots, Z_n).\n$$\nSUTVA rules out interference, if one person receives a vaccine, it should not directly change another person's health outcome. This assumption fails when treatment effects spill over across units (e.g., in network settings or when treated individuals interact with controls).\n\n*Assumption 2: Conditional Unconfoundedness (Ignorability).* Given the observed covariates, treatment assignment is independent of the potential outcomes:\n$$\n(Y_i(1), Y_i(0)) \\perp\\!\\!\\!\\perp Z_i \\mid X_i.\n$$ {#eq-ignorability}\n\nThis is the key \"no unmeasured confounders\" assumption. It says that once we condition on $X$, knowing whether $Z = 0$ or $Z = 1$ provides no additional information about the potential outcomes. Intuitively, within strata of $X$, treatment assignment is as good as random.\n\n*Assumption 3: Positivity (Overlap).* Every unit has a positive probability of receiving either treatment:\n$$\n0 < P(Z_i = 1 \\mid X_i = x) < 1 \\quad \\text{for all } x \\in \\mathcal{X}.\n$$ {#eq-positivity}\n\nPositivity ensures that we have both treated and control units at every covariate value. Without it, we cannot learn treatment effects in regions where everyone is treated (or no one is).\n\nUnder these three assumptions, the observed data $(X_i, Z_i, Y_i)_{i=1}^n$ are sufficient to identify causal effects. Ignorability allows us to write\n$$\nE[Y(z) \\mid X = x] = E[Y \\mid X = x, Z = z],\n$$\nwhich converts an unobservable quantity (the expected potential outcome) into an observable one (the conditional expectation of the observed outcome given covariates and treatment). This is the bridge from causal to statistical.\n\n\n## CATE and ATE {#sec-causal-cate}\n\nThe *conditional average treatment effect* (CATE) is the expected treatment effect for a unit with covariates $x$:\n$$\n\\tau(x) = E[Y(1) - Y(0) \\mid X = x] = E[Y \\mid X = x, Z = 1] - E[Y \\mid X = x, Z = 0].\n$$ {#eq-cate}\n\nThe CATE captures *heterogeneity* in treatment effects. A job training program might help workers without a college degree (large $\\tau(x)$) but provide little benefit to workers who already have advanced degrees (small $\\tau(x)$). Understanding this heterogeneity is essential for targeting interventions effectively.\n\nThe *average treatment effect* (ATE) is the population mean of the CATE:\n$$\n\\text{ATE} = E[\\tau(X)] = E[Y(1) - Y(0)] = \\int \\tau(x) \\, dP_X(x).\n$$ {#eq-ate}\n\nThe ATE tells us whether the treatment helps on average. It is the most commonly reported causal estimand, but it can be misleading when treatment effects are heterogeneous. An ATE of zero could mean the treatment has no effect on anyone, or it could mean it helps half the population and hurts the other half by equal amounts.\n\n### Beyond the mean: what QTEs reveal that CATEs miss {#sec-causal-qte-motivation}\n\nThe CATE and ATE summarize the treatment effect through the conditional *mean*. But the mean is only one summary of the outcome distribution. What if we want to know how the treatment affects the *entire distribution* of outcomes? This is where the GBC framework provides a distinctive advantage.\n\nTo see why the mean is not enough, consider a concrete example. Suppose a government job training program is evaluated on its effect on annual wages. The ATE might be \\$500, a modest and perhaps disappointing result. But this average conceals a more interesting story. At the 10th percentile of the wage distribution (the lowest earners), the program might shift wages from \\$0 to \\$4,000, a large effect for individuals who would otherwise have had zero labor income. At the 90th percentile (the highest earners), the program might have no effect at all, or even a slightly negative effect if it displaces time that would have been spent on more productive job search. The ATE of \\$500 is the average of a large positive effect at the bottom and a near-zero effect at the top, but it conveys neither the magnitude of the benefit to the most disadvantaged nor the irrelevance of the program for the most advantaged. This is precisely the kind of heterogeneity that the *quantile treatment effect* reveals.\n\nThe CATE $\\tau(x) = E[Y(1) - Y(0) \\mid X = x]$ captures heterogeneity across *covariates*, how the mean treatment effect varies across subgroups defined by age, education, or income. The QTE captures a fundamentally different kind of heterogeneity: variation across the *outcome distribution* for a fixed covariate profile. Two individuals with identical covariates $x$ can experience very different treatment effects because one happens to draw a favorable unobserved shock (high $\\tau$) and the other draws an unfavorable one (low $\\tau$). The CATE averages over these unobserved shocks; the QTE traces out how the treatment reshapes the distribution from which they are drawn.\n\nThe *quantile treatment effect* (QTE) at level $\\tau$ for a unit with covariates $x$ is\n$$\n\\text{QTE}(\\tau, x) = Q_{Y(1)}(\\tau \\mid x) - Q_{Y(0)}(\\tau \\mid x) = F^{-1}_{Y \\mid X=x, Z=1}(\\tau) - F^{-1}_{Y \\mid X=x, Z=0}(\\tau),\n$$ {#eq-qte}\nwhere the second equality uses the ignorability assumption. The QTE tells us how the treatment shifts the $\\tau$-th quantile of the outcome distribution. For instance, $\\text{QTE}(0.5, x)$ captures the effect on the median outcome, $\\text{QTE}(0.1, x)$ captures the effect on the lower tail (the worst-off 10%), and $\\text{QTE}(0.9, x)$ captures the effect on the upper tail (the best-off 10%). A treatment might have a modest median effect but a large effect in the tails, it could prevent catastrophic outcomes without much changing typical ones. This is common in medical treatments, where the primary goal is to reduce the probability of severe adverse events.\n\nThe CATE is recovered by integrating the QTE over quantile levels:\n$$\n\\tau(x) = \\int_0^1 \\text{QTE}(q, x) \\, dq.\n$$ {#eq-cate-from-qte}\n\nThis identity, which follows from the fact that the mean is the integral of the quantile function, links the GBC framework to classical causal estimands. The IQN learns the full quantile function $\\hat{Q}(q \\mid x, z)$. The QTE falls out immediately as the difference of two quantile evaluations. The CATE falls out as the integral (or average) of the QTE over quantile levels.\n\nIn policy applications, the QTE is often more decision-relevant than the CATE. A policymaker deciding whether to fund a job training program cares not only about the average wage gain but also about whether the program lifts the worst-off individuals out of poverty (the lower tail) and whether it creates a few spectacular successes (the upper tail). A Rawlsian social planner would focus on $\\text{QTE}(0.05, x)$, the effect on the 5th percentile, while a utilitarian would integrate across all quantile levels to recover the CATE. The GBC framework supports both perspectives from a single trained model, simply by evaluating the quantile function at different levels.\n\n::: {.callout-important appearance=\"simple\" title=\"Interpretive Caveat\"}\nThe QTE compares the same quantile of the *marginal* distributions under treatment and control. It does *not* tell us about the individual-level treatment effect at that quantile. In general,\n$$\nQ_{Y(1)}(\\tau \\mid x) - Q_{Y(0)}(\\tau \\mid x) \\neq Q_{Y(1) - Y(0)}(\\tau \\mid x).\n$$\nThe left side compares the $\\tau$-th quantile of outcomes under treatment to the $\\tau$-th quantile under control. The right side is the $\\tau$-th quantile of the treatment effect distribution itself. These are equal only under rank preservation, when the treatment does not change the rank ordering of individuals within their outcome distribution [@chernozhukov2005iv].\n:::\n\n\n## The Propensity Module {#sec-causal-propensity}\n\nThe *propensity score* is the probability of receiving treatment given covariates:\n$$\ne(x) = P(Z = 1 \\mid X = x).\n$$ {#eq-propensity}\n\n@rosenbaum1983central proved that under ignorability, conditioning on the scalar propensity score $e(x)$ is sufficient for removing confounding bias, even though $X$ may be high-dimensional. Formally, if $(Y(1), Y(0)) \\perp\\!\\!\\!\\perp Z \\mid X$, then $(Y(1), Y(0)) \\perp\\!\\!\\!\\perp Z \\mid e(X)$. The propensity score is a *balancing score*: within strata of $e(x)$, the distribution of covariates is the same for treated and control units.\n\nThis dimension-reduction property is precisely what makes the propensity score useful for GBC. Instead of learning the conditional quantile function in the full $p$-dimensional covariate space, we can condition on the scalar $e(x)$, or, more practically, include it as an additional feature.\n\nIn the GBC framework, we estimate the propensity score $\\hat{e}(x)$ and include it as an additional input to the IQN. The augmented input vector becomes\n$$\n\\tilde{x} = (x, \\hat{e}(x)) \\in \\mathbb{R}^{p+1},\n$$\nand the IQN learns the quantile function $\\hat{Q}(q, \\tilde{x}, z)$. This design follows @hahn2020bayesian, who showed that including $\\hat{e}(x)$ in the prognostic function of Bayesian Causal Forests addresses *regularization-induced confounding*: when the prior (or regularizer) pulls the treatment effect toward zero, strong confounding can bias the estimates unless the model explicitly adjusts for the propensity score.\n\nWhy include the propensity score as a *feature* rather than using it for reweighting? The GBC perspective is that $\\hat{e}(x)$ provides the network with a direct signal about how balanced the treatment and control groups are at each covariate value. In regions where $\\hat{e}(x) \\approx 0.5$ (good overlap), the network can learn treatment effects from abundant data on both sides. In regions where $\\hat{e}(x) \\approx 0$ or $1$ (poor overlap), the propensity score alerts the network that extrapolation is required.\n\nThe classical approach to using the propensity score is *inverse propensity weighting* (IPW). The Horvitz--Thompson estimator for the ATE is\n$$\n\\hat{\\tau}_{\\text{IPW}} = \\frac{1}{n} \\sum_{i=1}^n \\left[ \\frac{Z_i Y_i}{\\hat{e}(X_i)} - \\frac{(1 - Z_i) Y_i}{1 - \\hat{e}(X_i)} \\right].\n$$ {#eq-ipw}\n\nIPW reweights each observation by the inverse of its treatment probability, effectively creating a pseudo-population in which treatment assignment is independent of covariates. The trouble with IPW is that it can be extremely noisy when $\\hat{e}(x)$ is close to 0 or 1, extreme weights amplify estimation variance.\n\nGBC sidesteps this problem entirely. By including $\\hat{e}(x)$ as a feature, the network learns how to adjust for confounding *locally*, without explicit reweighting. The propensity score enters the quantile function as a smooth input, and the network learns to weight its influence appropriately at each covariate value. This is related to the *doubly robust* approach [@chernozhukov2018double], which combines outcome modeling with propensity weighting, but GBC achieves the adjustment through the architecture rather than through an explicit formula.\n\nIn practice, $e(x)$ is unknown and must be estimated from data. The simplest approach is logistic regression:\n$$\n\\hat{e}(x) = \\sigma(w^\\top x + b),\n$$\nwhere $\\sigma$ is the sigmoid function. For more complex propensity structures, a neural network can be used:\n\n::: {#8e5b97d6 .cell execution_count=2}\n``` {.python .cell-code code-fold=\"false\"}\nimport torch\nimport torch.nn as nn\n\nclass PropensityNet(nn.Module):\n    \"\"\"Simple MLP for propensity score estimation.\"\"\"\n    def __init__(self, input_dim, hidden_dim=64):\n        super().__init__()\n        self.net = nn.Sequential(\n            nn.Linear(input_dim, hidden_dim),\n            nn.ReLU(),\n            nn.Linear(hidden_dim, hidden_dim),\n            nn.ReLU(),\n            nn.Linear(hidden_dim, 1),\n            nn.Sigmoid()\n        )\n\n    def forward(self, x):\n        return self.net(x).squeeze(-1)\n\n# Example: 5 covariates\nprop_net = PropensityNet(input_dim=5)\nx_test = torch.randn(10, 5)\ne_hat = prop_net(x_test)\nprint(f\"Propensity scores: {e_hat[:5].detach().numpy().round(3)}\")\n```\n:::\n\n\nThe propensity network is trained using binary cross-entropy loss on the treatment labels:\n$$\n\\ell_\\pi = -\\frac{1}{n} \\sum_{i=1}^n \\left[ Z_i \\log \\hat{e}(X_i) + (1 - Z_i) \\log(1 - \\hat{e}(X_i)) \\right].\n$$ {#eq-propensity-loss}\n\nA well-calibrated propensity score is important for the downstream CATE estimation. If the propensity model is badly misspecified, the augmented IQN may inherit the bias. In practice, we recommend checking calibration by binning the estimated propensity scores and comparing the observed treatment rate within each bin to the average predicted probability. A well-calibrated model should produce a roughly linear relationship between predicted and observed treatment rates. When calibration is poor, it may help to use a more flexible propensity model (e.g., adding hidden layers) or to apply Platt scaling as a post-hoc correction.\n\n\n## The Composite Loss {#sec-causal-loss}\n\nThe GBC approach to causal inference trains a single IQN that takes as input the covariates $x$, the treatment indicator $z$, the estimated propensity score $\\hat{e}(x)$, and a quantile level $q \\sim \\text{Uniform}(0,1)$. The network outputs $\\hat{Q}(q, x, z, \\hat{e}(x))$, an estimate of the $q$-th conditional quantile of $Y$ given $(X, Z)$.\n\nTo train the outcome model effectively for causal estimation, we use a two-step procedure. We estimate the propensity score $\\hat{e}(x)$ in a first step using a separate network trained with binary cross-entropy. The estimated propensity is then included as an additional covariate when training the outcome model, which uses a two-part composite loss.\n\nThe outcome model training loss is\n$$\n\\mathcal{L} = \\mathcal{L}_{\\text{pinball}} + w_1 \\mathcal{L}_{\\text{MAE}},\n$$ {#eq-causal-loss}\nwhere the components are:\n\n*1. Pinball loss (quantile fidelity).* The core quantile regression loss:\n$$\n\\mathcal{L}_{\\text{pinball}} = \\frac{1}{n} \\sum_{i=1}^n \\rho_q(Y_i - \\hat{Q}(q, \\tilde{x}_i, Z_i)),\n$$\nwhere $\\rho_q(u) = u(q - \\mathbf{1}(u < 0))$ is the check function from @koenker1978regression. This ensures the network learns the conditional quantile function accurately. During training, $q$ is sampled uniformly from $(0, 1)$ at each minibatch, so the network sees the full range of quantile levels.\n\n*2. MAE anchor (mean accuracy).* A mean absolute error term that encourages the network's median prediction ($q = 0.5$) to track the conditional mean:\n$$\n\\mathcal{L}_{\\text{MAE}} = \\frac{1}{n} \\sum_{i=1}^n |Y_i - \\hat{Q}(0.5, \\tilde{x}_i, Z_i)|.\n$$\nThis stabilizes training by providing a \"ground truth\" anchor for the central tendency of the outcome distribution. Without it, the network might learn accurate quantiles in the tails but drift on the median.\n\nThe weight $w_1$ controls the relative importance of the MAE anchor. In practice, we find that $w_1 = 0.1$ works well across a range of settings.\n\nThe two-part loss is the GBC alternative to Double Machine Learning's orthogonalization strategy. DML achieves robustness to nuisance estimation errors through Neyman-orthogonal score functions and cross-fitting. GBC achieves a similar goal through the architecture: by jointly training the propensity and outcome components, the network learns to adjust for confounding in a way that is robust to moderate misspecification of either component.\n\nThe key difference is that DML constructs a *pseudo-outcome* that algebraically removes the effect of nuisance parameter estimation, while GBC lets the network learn the adjustment implicitly. DML's approach comes with strong theoretical guarantees. GBC's approach is more flexible but requires the network to have sufficient capacity to learn the confounding adjustment from data.\n\nPutting together the propensity module and the composite loss, the full GBC algorithm for causal inference is:\n\n::: {.callout-tip appearance=\"simple\" title=\"Algorithm 13.1: GBC for Causal Inference\"}\n*Input:* Observed data $(X_i, Z_i, Y_i)_{i=1}^n$.\n\n*Step 1 (Propensity).* Estimate $\\hat{e}(X_i) = \\hat{P}(Z = 1 \\mid X_i)$ via logistic regression or a neural network. Construct augmented covariates $\\tilde{X}_i = (X_i, \\hat{e}(X_i))$.\n\n*Step 2 (Train IQN).* Minimize the composite loss (@eq-causal-loss) with respect to the IQN parameters, using $\\hat{e}(X_i)$ as an additional input covariate. At each minibatch, sample $q \\sim \\text{Uniform}(0, 1)$ and compute $\\hat{Q}(q, \\tilde{X}_i, Z_i)$. The propensity is not re-estimated in this step; it enters only as a fixed covariate.\n\n*Step 3 (Infer).* For a new unit with covariates $x$, evaluate the QTE as $\\widehat{\\text{QTE}}(q, x) = \\hat{Q}(q, \\tilde{x}, 1) - \\hat{Q}(q, \\tilde{x}, 0)$ for any $q \\in (0,1)$. The CATE is obtained by averaging over a grid of quantile levels $\\mathcal{U} = \\{0.05, 0.15, \\ldots, 0.95\\}$: $\\hat{\\tau}(x) = \\frac{1}{|\\mathcal{U}|} \\sum_{q \\in \\mathcal{U}} \\widehat{\\text{QTE}}(q, x)$. Finally, the ATE is the average of the CATE over the test sample: $\\widehat{\\text{ATE}} = \\frac{1}{n_{\\text{test}}} \\sum_{j} \\hat{\\tau}(X_j)$.\n\n*Output:* $\\hat{\\tau}(x)$, $\\widehat{\\text{QTE}}(q, x)$, and the full conditional quantile function $\\hat{Q}(q, \\tilde{x}, z)$.\n:::\n\n\n## Semiparametric Efficiency {#sec-causal-efficiency}\n\nHow accurate can *any* estimator of the ATE or CATE be, regardless of the method used? The semiparametric efficiency bound provides the answer. This bound is the analogue of the Cramer--Rao lower bound for parametric models, but it applies in the semiparametric setting where we make minimal assumptions about the data-generating process beyond the three causal identification conditions (SUTVA, ignorability, positivity). Any estimator that achieves this bound extracts all available information from the data about the treatment effect, and no regular estimator can do better.\n\n@hahn1998role showed that the semiparametric variance bound for estimating the ATE $\\tau_0 = E[Y(1) - Y(0)]$ is\n$$\nV_{\\text{eff}} = E\\!\\left[ \\frac{\\text{Var}(Y(1) \\mid X)}{e(X)} + \\frac{\\text{Var}(Y(0) \\mid X)}{1 - e(X)} + (\\tau(X) - \\tau_0)^2 \\right].\n$$ {#eq-eff-bound}\n\nThe first two terms reflect the difficulty of estimating the conditional mean outcomes, they are large when the outcome variance is high or when the propensity score is extreme (poor overlap). The third term captures heterogeneity: it is zero when the treatment effect is constant and grows as heterogeneity increases. To build intuition, consider a randomized experiment with $e(x) = 0.5$ for all $x$, constant treatment effect $\\tau(x) = \\tau_0$, and homoskedastic outcomes with variance $\\sigma^2$ under both treatment arms. Then $V_{\\text{eff}} = 2\\sigma^2 / 0.5 + 2\\sigma^2 / 0.5 = 4\\sigma^2$, which is the familiar variance of the difference-in-means estimator. Confounding ($e(x)$ varying) and heterogeneity ($\\tau(x) \\neq \\tau_0$) both inflate the bound, making causal estimation fundamentally harder.\n\nAny regular estimator satisfies $\\sqrt{n}(\\hat{\\tau} - \\tau_0) \\xrightarrow{d} \\mathcal{N}(0, V)$ with $V \\geq V_{\\text{eff}}$. An estimator that achieves $V = V_{\\text{eff}}$ is called *semiparametrically efficient*.\n\nThe tool for constructing efficient estimators is the *efficient influence function* (EIF):\n$$\n\\psi(Y, Z, X; \\tau, \\eta) = \\frac{Z - e(X)}{e(X)(1 - e(X))} \\bigl(Y - \\mu_Z(X)\\bigr) + \\mu_1(X) - \\mu_0(X) - \\tau,\n$$ {#eq-eif}\nwhere $\\eta = (e(x), \\mu_0(x), \\mu_1(x))$ collects the nuisance functions: the propensity score and the conditional means $\\mu_z(x) = E[Y \\mid X = x, Z = z]$. The EIF has mean zero at the true parameter values, $E[\\psi(Y, Z, X; \\tau_0, \\eta_0)] = 0$, and the semiparametric variance bound equals $V_{\\text{eff}} = E[\\psi^2]$.\n\nA central property of the EIF is *Neyman orthogonality*: the derivative of its expectation with respect to the nuisance parameters vanishes at the truth:\n$$\n\\left. \\frac{\\partial}{\\partial \\eta} E[\\psi(Y, Z, X; \\tau_0, \\eta)] \\right|_{\\eta = \\eta_0} = 0.\n$$ {#eq-neyman}\n\nThis means that small errors in estimating the nuisance functions $e(x)$ and $\\mu_z(x)$ have only a *second-order* effect on the treatment effect estimate. This is the property that makes DML work: by using Neyman-orthogonal scores, DML achieves $\\sqrt{n}$-consistent ATE estimation even when the nuisance functions are estimated at slower-than-$\\sqrt{n}$ nonparametric rates.\n\nUnder regularity conditions, the GBC posterior for the ATE concentrates on the semiparametric efficiency bound. GBC pays *no asymptotic price* for estimating the full conditional quantile function rather than just the conditional mean. The additional distributional information, the QTE, the CDTE, the full shape of the outcome distribution under each treatment arm, comes for free. This is because the CATE is a one-dimensional projection (the integral) of the quantile function, and projecting a well-estimated high-dimensional object onto a lower-dimensional subspace does not increase the estimation error. The result relies on the semiparametric Bernstein--von Mises theorem [@castillo2014bernstein]:\n\n::: {.callout-tip appearance=\"simple\" title=\"Proposition 13.1: GBC Semiparametric Efficiency\"}\nLet $\\hat{\\tau}_{\\text{GBC}} = R^{-1} \\sum_{r=1}^R \\tau^{(r)}$ where $\\{\\tau^{(r)}\\}$ are draws from the GBC posterior, obtained by sampling $q^{(r)} \\sim \\text{Uniform}(0,1)$ and computing $\\tau^{(r)}(x) = \\hat{Q}(q^{(r)}, \\tilde{x}, 1) - \\hat{Q}(q^{(r)}, \\tilde{x}, 0)$. Under unconfoundedness, overlap, SUTVA, and the semiparametric BvM conditions:\n$$\n\\sqrt{n}\\,(\\hat{\\tau}_{\\text{GBC}} - \\tau_0) \\;\\xrightarrow{d}\\; \\mathcal{N}(0, V_{\\text{eff}}).\n$$\nMoreover, the GBC score is asymptotically Neyman-orthogonal, implying double robustness: the estimator remains $\\sqrt{n}$-consistent provided the product of the propensity score and outcome model convergence rates is $o(n^{-1/2})$.\n:::\n\nThe proof, detailed in @nareklishvili2026causal, proceeds in three steps. First, the semiparametric BvM theorem shows that the GBC posterior concentrates on a $\\sqrt{n}$-ball around the efficient estimator. Second, the efficient influence function $\\psi$ is shown to be orthogonal to the nuisance tangent space, which transfers Neyman orthogonality to the GBC estimator. Third, the double robustness follows because the GBC score is asymptotically equivalent to $\\psi$, and $\\psi$ satisfies the required product-rate condition.\n\nThe double robustness property deserves emphasis. It says that the GBC estimator of the ATE is $\\sqrt{n}$-consistent even if either the propensity score model *or* the outcome model is somewhat misspecified, as long as both are estimated at reasonable rates whose product satisfies the $o(n^{-1/2})$ condition. Concretely, if the propensity score converges at rate $n^{-1/4}$ and the outcome model converges at rate $n^{-1/4}$, their product converges at rate $n^{-1/2}$, which is just fast enough. If one converges faster, say $n^{-1/3}$, the other is allowed to converge more slowly ($n^{-1/6}$). This flexibility is what makes the approach robust to partial misspecification. In the GBC framework, double robustness arises from the architecture (the joint training of the propensity and outcome components) rather than from the explicit algebraic construction used by DML. The orthogonalization is *learned* rather than *imposed*.\n\n\n## Rate Advantage over DML {#sec-causal-dml}\n\nThe Double Machine Learning framework of @chernozhukov2018double uses a two-stage procedure to estimate treatment effects while removing confounding bias. In the first stage, DML estimates two nuisance functions: the propensity score $\\hat{m}(x) = \\hat{P}(Z = 1 \\mid X = x)$ and the outcome regression $\\hat{g}(x) = \\hat{E}[Y \\mid X = x]$. These can be estimated using any flexible machine learning method, random forests, gradient boosting, neural networks. The purpose of this first stage is to \"partial out\" the confounding: by predicting both the treatment and the outcome from confounders, DML isolates the residual variation that is attributable to the causal effect.\n\nIn the second stage, DML regresses the outcome residuals $Y_i - \\hat{g}(X_i)$ on the treatment residuals $Z_i - \\hat{m}(X_i)$ to estimate the treatment effect. The key theoretical insight is the *Neyman orthogonality* condition: the score function for the treatment effect parameter $\\theta_0$ is constructed so that its derivative with respect to the nuisance parameters vanishes at the truth. This means that first-stage estimation errors in $\\hat{g}$ and $\\hat{m}$ affect the treatment effect estimate only at second order, enabling $\\sqrt{n}$-consistent estimation of $\\theta_0$ even when the nuisance functions converge at slower nonparametric rates. DML also uses *cross-fitting* (sample splitting) to avoid overfitting bias: the nuisance functions are estimated on one fold of the data and the treatment effect is estimated on the other, then the roles are swapped and the estimates averaged.\n\nThe limitation of DML's most common specification, the partially linear regression (PLR) model $Y = \\theta_0 Z + g_0(X) + U$, is the assumption of a *constant* treatment effect $\\theta_0$. When the true CATE is heterogeneous, as in most real applications, the PLR specification yields a biased estimate that is a weighted average of the true CATE function. DML's interactive regression model (IRM) relaxes this assumption, but estimating the full CATE function $\\tau(x) = E[Y \\mid X = x, Z = 1] - E[Y \\mid X = x, Z = 0]$ in $p$ dimensions remains subject to the curse of dimensionality.\n\nWhen does GBC outperform DML for CATE estimation? The answer depends on the *dimensionality of confounding*. @stone1982optimal's minimax rate for nonparametric regression: for a $\\beta$-smooth function in $d$ dimensions, the optimal MSE rate is\n$$\n\\text{MSE} = O(n^{-2\\beta/(2\\beta + d)}).\n$$ {#eq-stone-rate}\n\nThis rate depends on $d$, the curse of dimensionality. Estimating a function in 20 dimensions is fundamentally harder than in 3 dimensions, regardless of the method used.\n\nThe GBC advantage arises when confounding is *low-dimensional*. Suppose there are $p$ observed covariates, but the treatment assignment and outcome depend on covariates only through $k$ latent directions ($k \\ll p$). @rosenbaum1983central showed that the propensity score itself is a one-dimensional sufficient statistic for treatment assignment. More generally, the confounding structure may involve $k$ directions, where $k$ is much smaller than $p$.\n\nDML's final-stage CATE learner operates in the full $p$-dimensional covariate space. GBC, by contrast, can operate in the $k$-dimensional latent space after dimension reduction via the propensity score embedding. Applying Stone's rate:\n\n$$\n\\text{MSE}_{\\text{DML}} = O(n^{-2\\beta/(2\\beta + p)}), \\qquad \\text{MSE}_{\\text{GBC}} = O(n^{-2\\beta/(2\\beta + k)}).\n$$ {#eq-rate-comparison}\n\nThe MSE ratio is\n$$\n\\frac{\\text{MSE}_{\\text{DML}}}{\\text{MSE}_{\\text{GBC}}} = O\\!\\left(n^{\\,\\frac{2\\beta(p - k)}{(2\\beta + k)(2\\beta + p)}}\\right).\n$$ {#eq-mse-ratio}\n\nThis ratio grows *without bound* as $n \\to \\infty$, meaning GBC's advantage increases with sample size when $k < p$.\n\nTo make this concrete, consider $\\beta = 2$ (twice-differentiable CATE function), $p = 20$ observed covariates, and $k = 3$ latent confounders. The rates are:\n$$\n\\text{DML RMSE rate} = O(n^{-1/12}), \\qquad \\text{GBC RMSE rate} = O(n^{-2/7}).\n$$\n\nThe exponent for GBC ($-2/7 \\approx -0.286$) is 3.4 times larger in magnitude than DML's ($-1/12 \\approx -0.083$). At selected sample sizes:\n\n| $n$ | MSE ratio (DML/GBC) | MSE reduction |\n|---:|---:|---:|\n| 200 | 8.5x | 88% |\n| 500 | 12.4x | 92% |\n| 1,000 | 16.4x | 94% |\n| 2,000 | 21.7x | 95% |\n\n: Theoretical MSE ratio between DML and GBC under low-dimensional confounding ($\\beta = 2$, $p = 20$, $k = 3$). The ratio grows as $n^{0.405}$. {#tbl-mse-ratio}\n\nThese are *asymptotic* predictions assuming equal multiplicative constants. In practice, finite-sample gains are smaller due to constant factors and estimation error in the dimension reduction step (see @sec-causal-simulation).\n\nThe rate advantage is amplified when the CATE function has *compositional structure*, when it can be written as a superposition of lower-dimensional functions. @schmidt-hieber2020nonparametric showed that deep ReLU networks with depth $L \\asymp \\log n$ achieve the rate\n$$\n\\text{MSE} \\leq C \\max_{i=0,\\ldots,J} n^{-2\\beta_i^*/(2\\beta_i^* + t_i)} \\log^3 n,\n$$ {#eq-compositional-rate}\nwhere $t_i$ is the effective input dimension of the $i$-th compositional layer and $\\beta_i^*$ are effective smoothness indices. For additive models ($t_i = 1$), the rate becomes $O(n^{-2\\beta/(2\\beta + 1)})$, which is *independent of the ambient dimension $p$*.\n\n@padilla2022quantile extended this result to quantile regression with the pinball loss, showing that the same compositional rates hold for conditional quantile estimation, even under heavy-tailed error distributions. This means the full distributional output of GBC comes at no statistical cost relative to point estimation.\n\nThe rate advantage requires three conditions. First, confounding must be low-dimensional ($k \\ll p$), since the gap disappears as $k \\to p$. In many applications this is plausible: treatment assignment depends on a handful of key variables (income, health status, geographic location) even when the analyst observes dozens of covariates. Second, dimension reduction must be accurate: the propensity score and any additional sufficient directions must be well estimated. If the dimension reduction step introduces substantial error, the finite-sample gains over DML will be smaller than the theory predicts. Third, the model must be correctly specified, because GBC's posterior depends on the forward simulator, whereas DML's orthogonalization is more robust to misspecification of the individual nuisance components.\n\nWhen these conditions are met, GBC can achieve substantially lower CATE estimation error than DML, especially at moderate sample sizes. In settings where these conditions fail, for instance, when confounding is genuinely high-dimensional or when the data-generating process is poorly understood, DML's orthogonalization offers a safer default.\n\n\n## LaLonde Benchmark {#sec-causal-lalonde}\n\nFor the LaLonde analysis, we report the *marginal* QTE, defined as $\\text{QTE}(\\tau) = Q_{Y(1)}(\\tau) - Q_{Y(0)}(\\tau)$ where the quantiles are over the marginal outcome distributions, this differs from the conditional QTE $\\text{QTE}(\\tau, x)$ at a specific covariate value.\n\nThe LaLonde dataset is the gold standard benchmark in causal inference [@lalonde1986evaluating; @dehejia1999causal]. It evaluates the effect of the National Supported Work (NSW) job training program, a randomized experiment that provided training and work experience to disadvantaged workers in the 1970s. The experimental benchmark estimates that the program increased earnings by roughly \\$1,500--\\$2,000 in 1978 dollars.\n\nThe dataset contains $n = 445$ observations with covariates including age, years of education, race indicators (Black, Hispanic), marital status, high school dropout indicator, and prior earnings in 1974 and 1975. The outcome is real earnings in 1978. Following the econometrics literature, we use the log-transformed outcome $\\log(\\text{re78} + 1)$, which produces a more normally distributed response and treatment effects interpretable as approximate percentage changes.\n\nWe compare three methods: DML (partially linear regression with random forest nuisance estimation using 500 trees at max depth 5 and 5-fold cross-fitting), BCF (Bayesian Causal Forests [@hahn2020bayesian] with logistic regression propensity scores and MCMC posterior sampling), and GBC (a quantile neural network with cosine embedding, propensity score augmentation, and the composite loss).\n\n::: {#tbl-lalonde-results .cell tbl-cap='Treatment effect estimates on the LaLonde dataset (log earnings, n=445). All three methods find positive treatment effects. DML reports a frequentist SE; BCF reports a Bayesian posterior SD; GBC reports the cross-quantile SD of the ATE across quantile levels.' execution_count=3}\n``` {.python .cell-code code-fold=\"true\"}\nimport pandas as pd\n\ndata = {\n    'Method': ['DML (PLR)', 'BCF', 'GBC (IQN)'],\n    'ATE': [0.995, 0.778, 0.862],\n    'Uncertainty': ['0.393 (SE)', '0.410 (post. SD)', '0.350 (cross-q SD)'],\n    '95% Interval': ['[0.225, 1.764]', '[-0.004, 1.541]', '[0.180, 1.530]'],\n    'Time (sec)': [1.8, 396, 186]\n}\ndf = pd.DataFrame(data)\ndf.style.hide(axis='index').set_properties(**{'text-align': 'center'})\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<style type=\"text/css\">\n#T_ee6b9_row0_col0, #T_ee6b9_row0_col1, #T_ee6b9_row0_col2, #T_ee6b9_row0_col3, #T_ee6b9_row0_col4, #T_ee6b9_row1_col0, #T_ee6b9_row1_col1, #T_ee6b9_row1_col2, #T_ee6b9_row1_col3, #T_ee6b9_row1_col4, #T_ee6b9_row2_col0, #T_ee6b9_row2_col1, #T_ee6b9_row2_col2, #T_ee6b9_row2_col3, #T_ee6b9_row2_col4 {\n  text-align: center;\n}\n</style>\n<table id=\"T_ee6b9\">\n  <thead>\n    <tr>\n      <th id=\"T_ee6b9_level0_col0\" class=\"col_heading level0 col0\" >Method</th>\n      <th id=\"T_ee6b9_level0_col1\" class=\"col_heading level0 col1\" >ATE</th>\n      <th id=\"T_ee6b9_level0_col2\" class=\"col_heading level0 col2\" >Uncertainty</th>\n      <th id=\"T_ee6b9_level0_col3\" class=\"col_heading level0 col3\" >95% Interval</th>\n      <th id=\"T_ee6b9_level0_col4\" class=\"col_heading level0 col4\" >Time (sec)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_ee6b9_row0_col0\" class=\"data row0 col0\" >DML (PLR)</td>\n      <td id=\"T_ee6b9_row0_col1\" class=\"data row0 col1\" >0.995000</td>\n      <td id=\"T_ee6b9_row0_col2\" class=\"data row0 col2\" >0.393 (SE)</td>\n      <td id=\"T_ee6b9_row0_col3\" class=\"data row0 col3\" >[0.225, 1.764]</td>\n      <td id=\"T_ee6b9_row0_col4\" class=\"data row0 col4\" >1.800000</td>\n    </tr>\n    <tr>\n      <td id=\"T_ee6b9_row1_col0\" class=\"data row1 col0\" >BCF</td>\n      <td id=\"T_ee6b9_row1_col1\" class=\"data row1 col1\" >0.778000</td>\n      <td id=\"T_ee6b9_row1_col2\" class=\"data row1 col2\" >0.410 (post. SD)</td>\n      <td id=\"T_ee6b9_row1_col3\" class=\"data row1 col3\" >[-0.004, 1.541]</td>\n      <td id=\"T_ee6b9_row1_col4\" class=\"data row1 col4\" >396.000000</td>\n    </tr>\n    <tr>\n      <td id=\"T_ee6b9_row2_col0\" class=\"data row2 col0\" >GBC (IQN)</td>\n      <td id=\"T_ee6b9_row2_col1\" class=\"data row2 col1\" >0.862000</td>\n      <td id=\"T_ee6b9_row2_col2\" class=\"data row2 col2\" >0.350 (cross-q SD)</td>\n      <td id=\"T_ee6b9_row2_col3\" class=\"data row2 col3\" >[0.180, 1.530]</td>\n      <td id=\"T_ee6b9_row2_col4\" class=\"data row2 col4\" >186.000000</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\nAll three methods find a positive treatment effect. The DML estimate of 0.995 on the log scale corresponds to roughly $e^{0.995} - 1 \\approx 170\\%$; BCF yields 0.778 (118%); GBC estimates 0.862 (137%). The large percentage changes reflect the log transformation applied to a population with many zero-earnings control observations.\n\nBCF and GBC both provide individual-level CATE estimates, enabling us to examine whether treatment effects vary across subgroups.\n\n::: {#tbl-heterogeneity .cell tbl-cap='Heterogeneity in estimated treatment effects on the LaLonde data. Both BCF and GBC find that the top quartile benefits roughly 3x more than the bottom quartile.' execution_count=4}\n``` {.python .cell-code code-fold=\"true\"}\nimport pandas as pd\nimport numpy as np\n\ndata = {\n    'Subgroup': ['Overall', 'Top quartile', 'Bottom quartile',\n                 'High education', 'Low education'],\n    'BCF CATE': [0.78, 1.10, 0.51, 0.85, 0.68],\n    'BCF % change': ['118%', '200%', '67%', '134%', '97%'],\n    'GBC CATE': [0.86, 1.15, 0.55, 0.92, 0.78],\n    'GBC % change': ['136%', '216%', '73%', '151%', '118%'],\n}\ndf = pd.DataFrame(data)\ndf.style.hide(axis='index').set_properties(**{'text-align': 'center'})\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<style type=\"text/css\">\n#T_21301_row0_col0, #T_21301_row0_col1, #T_21301_row0_col2, #T_21301_row0_col3, #T_21301_row0_col4, #T_21301_row1_col0, #T_21301_row1_col1, #T_21301_row1_col2, #T_21301_row1_col3, #T_21301_row1_col4, #T_21301_row2_col0, #T_21301_row2_col1, #T_21301_row2_col2, #T_21301_row2_col3, #T_21301_row2_col4, #T_21301_row3_col0, #T_21301_row3_col1, #T_21301_row3_col2, #T_21301_row3_col3, #T_21301_row3_col4, #T_21301_row4_col0, #T_21301_row4_col1, #T_21301_row4_col2, #T_21301_row4_col3, #T_21301_row4_col4 {\n  text-align: center;\n}\n</style>\n<table id=\"T_21301\">\n  <thead>\n    <tr>\n      <th id=\"T_21301_level0_col0\" class=\"col_heading level0 col0\" >Subgroup</th>\n      <th id=\"T_21301_level0_col1\" class=\"col_heading level0 col1\" >BCF CATE</th>\n      <th id=\"T_21301_level0_col2\" class=\"col_heading level0 col2\" >BCF % change</th>\n      <th id=\"T_21301_level0_col3\" class=\"col_heading level0 col3\" >GBC CATE</th>\n      <th id=\"T_21301_level0_col4\" class=\"col_heading level0 col4\" >GBC % change</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_21301_row0_col0\" class=\"data row0 col0\" >Overall</td>\n      <td id=\"T_21301_row0_col1\" class=\"data row0 col1\" >0.780000</td>\n      <td id=\"T_21301_row0_col2\" class=\"data row0 col2\" >118%</td>\n      <td id=\"T_21301_row0_col3\" class=\"data row0 col3\" >0.860000</td>\n      <td id=\"T_21301_row0_col4\" class=\"data row0 col4\" >136%</td>\n    </tr>\n    <tr>\n      <td id=\"T_21301_row1_col0\" class=\"data row1 col0\" >Top quartile</td>\n      <td id=\"T_21301_row1_col1\" class=\"data row1 col1\" >1.100000</td>\n      <td id=\"T_21301_row1_col2\" class=\"data row1 col2\" >200%</td>\n      <td id=\"T_21301_row1_col3\" class=\"data row1 col3\" >1.150000</td>\n      <td id=\"T_21301_row1_col4\" class=\"data row1 col4\" >216%</td>\n    </tr>\n    <tr>\n      <td id=\"T_21301_row2_col0\" class=\"data row2 col0\" >Bottom quartile</td>\n      <td id=\"T_21301_row2_col1\" class=\"data row2 col1\" >0.510000</td>\n      <td id=\"T_21301_row2_col2\" class=\"data row2 col2\" >67%</td>\n      <td id=\"T_21301_row2_col3\" class=\"data row2 col3\" >0.550000</td>\n      <td id=\"T_21301_row2_col4\" class=\"data row2 col4\" >73%</td>\n    </tr>\n    <tr>\n      <td id=\"T_21301_row3_col0\" class=\"data row3 col0\" >High education</td>\n      <td id=\"T_21301_row3_col1\" class=\"data row3 col1\" >0.850000</td>\n      <td id=\"T_21301_row3_col2\" class=\"data row3 col2\" >134%</td>\n      <td id=\"T_21301_row3_col3\" class=\"data row3 col3\" >0.920000</td>\n      <td id=\"T_21301_row3_col4\" class=\"data row3 col4\" >151%</td>\n    </tr>\n    <tr>\n      <td id=\"T_21301_row4_col0\" class=\"data row4 col0\" >Low education</td>\n      <td id=\"T_21301_row4_col1\" class=\"data row4 col1\" >0.680000</td>\n      <td id=\"T_21301_row4_col2\" class=\"data row4 col2\" >97%</td>\n      <td id=\"T_21301_row4_col3\" class=\"data row4 col3\" >0.780000</td>\n      <td id=\"T_21301_row4_col4\" class=\"data row4 col4\" >118%</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\nBoth methods find substantial heterogeneity. The top quartile of estimated CATEs shows roughly three times the percentage-change effect compared to the bottom quartile (200--216% vs. 67--73%). The education-based split reveals that individuals with above-median education benefit more from the training program, consistent with the human capital complementarity hypothesis: those with a basic educational foundation are better positioned to capitalize on job training.\n\nGBC reports higher CATE heterogeneity (SD = 0.52 vs. 0.24 for BCF) because the quantile treatment effects capture distributional variation in addition to covariate-driven heterogeneity.\n\nThe distinctive contribution of GBC is the ability to examine how the treatment reshapes the *entire* outcome distribution. On the LaLonde data, we can ask: does the NSW program mainly help at the median, or does it also lift the lower tail (preventing zero earnings)?\n\nThe quantile treatment effect profile $\\widehat{\\text{QTE}}(q)$ averaged over the sample reveals that the treatment effect is largest at low quantile levels ($q = 0.05$ to $0.3$), suggesting that the program's primary benefit is preventing the worst outcomes, moving individuals from zero earnings to positive earnings. At higher quantiles ($q > 0.7$), the effect is smaller: the program does not dramatically change outcomes for individuals who would have found employment anyway.\n\nThis pattern, large effects in the lower tail, modest effects at the median and above, has direct policy implications. If the goal of the NSW program is to reduce poverty (a lower-tail objective), the QTE analysis suggests it is highly effective: it lifts the floor on earnings for the most disadvantaged workers. If the goal is to increase average productivity (a mean objective), the program is moderately effective. If the goal is to create high earners (an upper-tail objective), the program has little impact. These are three different policy questions, all answered by a single trained GBC model simply by evaluating the quantile function at different levels. No retraining is needed; no additional assumptions are required.\n\nThis distributional insight is invisible to DML (which reports only a single ATE) and partially visible to BCF (which models the conditional *mean* treatment effect but not the conditional *distribution* of treatment effects across quantile levels).\n\n\n## IHDP Benchmark {#sec-causal-ihdp}\n\nThe Infant Health and Development Program (IHDP) dataset [@hill2011bayesian] is the standard held-out benchmark for causal ML methods, providing a comparison point against the broader literature on heterogeneous treatment effect estimation.\n\n*Data.* The original IHDP study enrolled 985 low-birth-weight, premature infants and randomly assigned 608 to intensive high-quality childcare and 377 to a control condition. The outcome is cognitive test score at age 3. Following @hill2011bayesian and @shalit2017estimating, the benchmark uses a semi-synthetic version: the 25 baseline covariates (birth weight, weeks premature, mother's education and employment, etc.) are real; potential outcomes under both treatment arms are generated from a response surface model, so the true CATE is known. We use 1,000 train/test splits from the standard benchmark of @shalit2017estimating, available via `econml.datasets.ihdp`.\n\n*Metric.* The standard metric is the Precision in Estimation of Heterogeneous Effects (PEHE):\n$$\n\\text{PEHE} = \\sqrt{\\frac{1}{n}\\sum_{i=1}^n \\bigl(\\hat{\\tau}(x_i) - \\tau(x_i)\\bigr)^2},\n$$ {#eq-pehe}\nwhere $\\tau(x) = \\mathbb{E}[Y(1) - Y(0) \\mid X = x]$ is the true CATE and $\\hat{\\tau}(x)$ is the estimated CATE.\n\n*GBC implementation.* We train separate IQNs for the treatment and control arms:\n\n::: {#8efc503d .cell execution_count=5}\n``` {.python .cell-code}\nfrom econml.datasets import ihdp\nimport numpy as np\nimport torch\nimport torch.nn as nn\n\nX_ihdp, T_ihdp, Y_ihdp, Y_cf_ihdp, mu0_ihdp, mu1_ihdp = ihdp(1, return_counterfactual=True)\n\n# Split into treatment and control\nidx_T = np.where(T_ihdp == 1)[0]\nidx_C = np.where(T_ihdp == 0)[0]\nX_T, Y_T = X_ihdp[idx_T], Y_ihdp[idx_T].reshape(-1, 1)\nX_C, Y_C = X_ihdp[idx_C], Y_ihdp[idx_C].reshape(-1, 1)\n\ndef train_iqn_arm(X_arm, Y_arm, epochs=1000):\n    n, d = X_arm.shape\n    xm, xs = X_arm.mean(0), X_arm.std(0) + 1e-8\n    ym, ys = Y_arm.mean(), Y_arm.std()\n    Xn = torch.tensor((X_arm - xm) / xs, dtype=torch.float32)\n    Yn = torch.tensor((Y_arm - ym) / ys, dtype=torch.float32)\n    model = IQN(xdim=d, hdim=256, M=64)\n    opt = torch.optim.Adam(model.parameters(), lr=2e-4)\n    for _ in range(epochs):\n        idx = torch.randperm(n)[:min(256, n)]\n        x_b, y_b = Xn[idx], Yn[idx]\n        tau = torch.rand(len(idx), 1)\n        r = y_b - model(x_b, tau)\n        loss = torch.mean(torch.maximum(tau * r, (tau - 1) * r))\n        opt.zero_grad(); loss.backward(); opt.step()\n    return model, xm, xs, ym, ys\n\nmodel_T, xm_T, xs_T, ym_T, ys_T = train_iqn_arm(X_T, Y_T)\nmodel_C, xm_C, xs_C, ym_C, ys_C = train_iqn_arm(X_C, Y_C)\n\ndef predict_cate(X_test):\n    model_T.eval(); model_C.eval()\n    XT = torch.tensor((X_test - xm_T) / xs_T, dtype=torch.float32)\n    XC = torch.tensor((X_test - xm_C) / xs_C, dtype=torch.float32)\n    tau_med = torch.tensor([[0.5]])\n    with torch.no_grad():\n        q_T = np.array([model_T(XT[i:i+1], tau_med).item() for i in range(len(X_test))])\n        q_C = np.array([model_C(XC[i:i+1], tau_med).item() for i in range(len(X_test))])\n    return q_T * ys_T.item() + ym_T.item() - (q_C * ys_C.item() + ym_C.item())\n\ncate_hat = predict_cate(X_ihdp)\ntau_true = mu1_ihdp - mu0_ihdp\npehe = np.sqrt(np.mean((cate_hat - tau_true)**2))\n```\n:::\n\n\n*Results.* Averaged over 100 train/test splits of the semi-synthetic benchmark, GBC achieves $\\sqrt{\\text{PEHE}} \\approx 1.8 \\pm 0.3$, comparable to CFRNet [@shalit2017estimating] ($\\sqrt{\\text{PEHE}} \\approx 1.7 \\pm 0.2$) and better than TARNet ($\\sqrt{\\text{PEHE}} \\approx 2.1 \\pm 0.3$). Full cached results are at `cache/ihdp_results.json`.\n\nBeyond the mean PEHE, GBC provides QTEs for the IHDP. The treatment effect distribution is right-skewed: most infants benefit modestly, but a subset (roughly the bottom quartile by $Y(0)$) benefits substantially. This distributional pattern is invisible to TARNet and CFRNet, which estimate only the conditional mean treatment effect. The IHDP benchmark thus confirms that GBC is competitive on the standard causal ML benchmark metric while providing strictly richer outputs.\n\n::: {.callout-note appearance=\"simple\"}\nThe IHDP dataset requires `pip install econml`. The semi-synthetic version with counterfactuals is accessed via `econml.datasets.ihdp(trial, return_counterfactual=True)`, where `trial` $\\in \\{1, \\ldots, 1000\\}$ indexes the simulation.\n:::\n\n\n## Simulation Study {#sec-causal-simulation}\n\nTo validate the GBC approach under controlled conditions, we design a simulation study with known ground truth. This allows us to assess the accuracy of CATE estimation, something we cannot do with the LaLonde data, where the true CATE is unknown. We generate $n = 1000$ observations with $p = 3$ covariates:\n\n::: {#123fe9bc .cell execution_count=6}\n``` {.python .cell-code code-fold=\"false\"}\nimport numpy as np\nimport torch\nimport torch.nn as nn\nnp.random.seed(42)\ntorch.manual_seed(42)\n\nn = 1000\np = 3\n\n# Covariates\nX = np.random.uniform(0, 2, size=(n, p))\n\n# Propensity score: nonlinear function of covariates\ndef true_propensity(X):\n    mu = -6 + (X[:, 0] > X[:, 1]).astype(float) + 6 * np.abs(X[:, 1] - 1)\n    return 1 / (1 + np.exp(-mu))\n\ne_true = true_propensity(X)\nZ = np.random.binomial(1, e_true)\n\n# True CATE: heterogeneous treatment effect\ndef true_cate(X):\n    return 1.0 + 2.0 * np.sin(np.pi * X[:, 0] / 2) - 1.5 * X[:, 1]\n\ntau_true = true_cate(X)\n\n# Potential outcomes\nmu0 = 3 * X[:, 0] + 2 * X[:, 1]**2 - X[:, 2]\nY0 = mu0 + np.random.normal(0, 1, n)\nY1 = mu0 + tau_true + np.random.normal(0, 1, n)\n\n# Observed outcome\nY = Z * Y1 + (1 - Z) * Y0\n\nprint(f\"Sample size: {n}\")\nprint(f\"Treatment rate: {Z.mean():.3f}\")\nprint(f\"True ATE: {tau_true.mean():.3f}\")\nprint(f\"True CATE range: [{tau_true.min():.2f}, {tau_true.max():.2f}]\")\n```\n:::\n\n\nThis design features several realistic challenges: the treatment probability depends on an indicator function and an absolute value, producing extreme propensity scores near 0 and 1; the CATE depends on $X_0$ through a sine function and on $X_1$ linearly, creating rich heterogeneity; and the baseline outcome $\\mu_0$ includes a squared term, giving a nonlinear response surface.\n\nWe implement the GBC causal model step by step.\n\n*Step 1: Estimate the propensity score.*\n\n::: {#0b905e4b .cell execution_count=7}\n``` {.python .cell-code code-fold=\"false\"}\n# Convert to tensors\nX_tensor = torch.tensor(X, dtype=torch.float32)\nZ_tensor = torch.tensor(Z, dtype=torch.float32)\nY_tensor = torch.tensor(Y, dtype=torch.float32)\n\n# Train propensity network\nprop_net = PropensityNet(input_dim=p, hidden_dim=64)\noptimizer = torch.optim.Adam(prop_net.parameters(), lr=0.001)\nloss_fn = nn.BCELoss()\n\nfor epoch in range(500):\n    e_hat = prop_net(X_tensor)\n    loss = loss_fn(e_hat, Z_tensor)\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()\n\nwith torch.no_grad():\n    e_hat = prop_net(X_tensor).numpy()\n\nprint(f\"Propensity score range: [{e_hat.min():.3f}, {e_hat.max():.3f}]\")\nprint(f\"Propensity correlation with truth: {np.corrcoef(e_true, e_hat)[0,1]:.3f}\")\n```\n:::\n\n\n*Step 2: Train the causal IQN.*\n\n::: {#390d6ace .cell execution_count=8}\n``` {.python .cell-code code-fold=\"false\"}\nclass CosineEmbedding(nn.Module):\n    def __init__(self, M=64, d=128):\n        super().__init__()\n        self.M = M\n        self.fc = nn.Sequential(nn.Linear(M, d), nn.ReLU())\n\n    def forward(self, tau):\n        i = torch.arange(1, self.M + 1, dtype=torch.float32)\n        cos_features = torch.cos(torch.pi * tau.unsqueeze(-1) * i)\n        return self.fc(cos_features)\n\n\nclass CausalIQN(nn.Module):\n    \"\"\"IQN for causal inference with propensity augmentation.\"\"\"\n    def __init__(self, input_dim, hidden_dim=128, M=64):\n        super().__init__()\n        # Covariate encoder: x, z, e(x)\n        self.x_encoder = nn.Sequential(\n            nn.Linear(input_dim + 2, hidden_dim),  # +2 for z and e(x)\n            nn.ReLU(),\n            nn.Linear(hidden_dim, hidden_dim),\n            nn.ReLU()\n        )\n        # Quantile encoder\n        self.tau_encoder = CosineEmbedding(M=M, d=hidden_dim)\n        # Output head\n        self.head = nn.Sequential(\n            nn.Linear(hidden_dim, hidden_dim),\n            nn.ReLU(),\n            nn.Linear(hidden_dim, 1)\n        )\n\n    def forward(self, x, z, e, tau):\n        # Concatenate covariates with treatment and propensity\n        x_aug = torch.cat([x, z.unsqueeze(-1), e.unsqueeze(-1)], dim=-1)\n        h_x = self.x_encoder(x_aug)\n        h_tau = self.tau_encoder(tau)\n        h = h_x * h_tau  # multiplicative merge\n        return self.head(h).squeeze(-1)\n\n\ndef pinball_loss(y, y_hat, tau):\n    \"\"\"Check (pinball) loss for quantile regression.\"\"\"\n    diff = y - y_hat\n    return torch.mean(torch.max(tau * diff, (tau - 1) * diff))\n\n\n# Training\nmodel = CausalIQN(input_dim=p, hidden_dim=128)\noptimizer = torch.optim.Adam(model.parameters(), lr=0.001)\nscheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=2000)\ne_hat_tensor = torch.tensor(e_hat, dtype=torch.float32)\n\nlosses = []\nfor epoch in range(2000):\n    tau = torch.rand(n)\n    y_hat = model(X_tensor, Z_tensor, e_hat_tensor, tau)\n\n    # Two-part loss (propensity enters as input covariate, not in loss)\n    l_pinball = pinball_loss(Y_tensor, y_hat, tau)\n    l_mae = torch.mean(torch.abs(Y_tensor - model(\n        X_tensor, Z_tensor, e_hat_tensor,\n        0.5 * torch.ones(n))))\n    loss = l_pinball + 0.1 * l_mae\n\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()\n    scheduler.step()\n    losses.append(loss.item())\n\nprint(f\"Final loss: {losses[-1]:.4f}\")\n```\n:::\n\n\n*Step 3: Estimate CATE and QTE.*\n\n::: {#c00eebb3 .cell execution_count=9}\n``` {.python .cell-code code-fold=\"false\"}\n# Estimate CATE by averaging QTE over quantile grid\nq_grid = torch.linspace(0.05, 0.95, 10)\n\nwith torch.no_grad():\n    cate_hat = torch.zeros(n)\n    for q_val in q_grid:\n        tau_q = q_val * torch.ones(n)\n        y1_hat = model(X_tensor, torch.ones(n), e_hat_tensor, tau_q)\n        y0_hat = model(X_tensor, torch.zeros(n), e_hat_tensor, tau_q)\n        cate_hat += (y1_hat - y0_hat)\n    cate_hat /= len(q_grid)\n\ncate_hat_np = cate_hat.numpy()\ncate_rmse = np.sqrt(np.mean((cate_hat_np - tau_true)**2))\ncate_bias = np.mean(cate_hat_np) - np.mean(tau_true)\n\nprint(f\"True ATE:      {tau_true.mean():.3f}\")\nprint(f\"Estimated ATE: {cate_hat_np.mean():.3f}\")\nprint(f\"ATE bias:      {cate_bias:.3f}\")\nprint(f\"CATE RMSE:     {cate_rmse:.3f}\")\nprint(f\"CATE corr:     {np.corrcoef(tau_true, cate_hat_np)[0,1]:.3f}\")\n```\n:::\n\n\n::: {#cell-fig-cate-scatter .cell execution_count=10}\n``` {.python .cell-code code-fold=\"true\"}\nimport matplotlib.pyplot as plt\n\nfig, axes = plt.subplots(1, 2, figsize=(10, 4))\n\n# Panel 1: True vs estimated CATE\nax = axes[0]\nax.scatter(tau_true, cate_hat_np, alpha=0.3, s=10, color='steelblue')\nlims = [min(tau_true.min(), cate_hat_np.min()) - 0.5,\n        max(tau_true.max(), cate_hat_np.max()) + 0.5]\nax.plot(lims, lims, 'k--', alpha=0.5, label='45-degree line')\nax.set_xlabel('True CATE')\nax.set_ylabel('Estimated CATE')\nax.set_title(f'CATE: RMSE = {cate_rmse:.3f}')\nax.legend(fontsize=8)\n\n# Panel 2: QTE profile\nax = axes[1]\nq_fine = torch.linspace(0.05, 0.95, 50)\nqte_profile = []\nwith torch.no_grad():\n    for q_val in q_fine:\n        tau_q = q_val * torch.ones(n)\n        y1 = model(X_tensor, torch.ones(n), e_hat_tensor, tau_q)\n        y0 = model(X_tensor, torch.zeros(n), e_hat_tensor, tau_q)\n        qte_profile.append((y1 - y0).mean().item())\n\nax.plot(q_fine.numpy(), qte_profile, 'b-', linewidth=2, label='Estimated QTE')\nax.axhline(y=tau_true.mean(), color='r', linestyle='--', label=f'True ATE = {tau_true.mean():.2f}')\nax.set_xlabel('Quantile level q')\nax.set_ylabel('Average QTE(q)')\nax.set_title('Quantile Treatment Effect Profile')\nax.legend(fontsize=8)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![True vs. estimated CATE on the simulation study. Each point is one unit. The correlation indicates how well the GBC model captures the heterogeneity in treatment effects.](ch13-causal_files/figure-html/fig-cate-scatter-output-1.png){#fig-cate-scatter width=950 height=374}\n:::\n:::\n\n\n@nareklishvili2026causal provide an extensive comparison on this simulation design. The key findings are:\n\n| Method | ATE | ATE Bias | CATE RMSE | Time (sec) |\n|-----|-----|-------|--------|------|\n| DML (PLR) | 2.636 | 1.711 | N/A | 2 |\n| BCF | 1.050 | 0.126 | 1.605 | 1155 |\n| GBC (IQN) | 1.400 | 0.475 | 1.372 | 89 |\n\n: Method comparison on simulated data ($n = 1000$, $p = 3$, population ATE = 1.0). DML's partially linear model assumption leads to large bias under this nonlinear design. BCF achieves the lowest ATE bias. GBC achieves the lowest CATE RMSE. {#tbl-sim-comparison}\n\nSeveral patterns emerge. DML suffers under nonlinearity: the partially linear model $Y = \\theta D + g(X) + \\varepsilon$ imposes a *constant* treatment effect, which is a severe misspecification when the true CATE is highly nonlinear, leading to an ATE bias of 1.711 (DML's interactive regression model would reduce this bias, but the standard PLR specification fails here). BCF excels at ATE, as the BART priors provide natural regularization and handle the near-violations of positivity gracefully, achieving the lowest ATE bias (0.126). GBC excels at CATE, with the quantile network capturing individual-level heterogeneity more effectively than BCF's tree-based approach (CATE RMSE of 1.372 vs. 1.605). Finally, GBC uniquely provides distributional information: the cross-quantile SD (0.841) captures genuine distributional heterogeneity in treatment effects, information that neither DML nor BCF provides.\n\nNo single method dominates across all metrics. If the analyst's primary goal is an unbiased ATE estimate with posterior uncertainty quantification, BCF is the best choice despite its computational cost. If the goal is individual-level treatment effect prediction or distributional analysis, GBC provides the richest output at an intermediate computational cost. If the goal is speed and simplicity for a one-time ATE estimate, DML remains attractive, provided the analyst is willing to accept the constant-effect assumption of the PLR specification or to use the more flexible IRM variant. The choice among these methods depends on what questions the analyst wants to answer.\n\nTo validate the theoretical rate advantage of @sec-causal-dml, @nareklishvili2026causal designed a simulation with $p = 20$ observed covariates and $k = 3$ latent confounders. The results across sample sizes confirm the theoretical predictions:\n\n| $n$ | GBC RMSE | DML RMSE | DML/GBC Ratio |\n|----:|-------|-------|:-------:|\n| 500 | 1.923 | 3.257 | 1.69 |\n| 1,000 | 1.764 | 2.458 | 1.39 |\n| 2,000 | 1.591 | 1.992 | 1.25 |\n| 5,000 | 1.490 | 1.496 | 1.00 |\n\n: GBC vs. DML under low-dimensional confounding ($k = 3$, $p = 20$). GBC dominates at moderate sample sizes; the advantage diminishes as $n$ grows because DML eventually learns the relevant features from abundant data. {#tbl-rate-validation}\n\nAt $n = 500$, GBC achieves 41% lower RMSE than DML (ratio 1.69). By $n = 5{,}000$, the methods are tied (ratio 1.00). This is consistent with the theory: GBC's rate advantage is asymptotically growing, but finite-sample gains are modulated by the accuracy of the dimension reduction step. An \"oracle\" GBC that uses the true latent confounders maintains a 3.2x advantage even at $n = 5{,}000$, suggesting that improved dimension reduction is the key bottleneck.\n\n\n## Simulation with Distributional Treatment Effects {#sec-causal-dist-sim}\n\nThe simulation in @sec-causal-simulation used a design where the treatment shifted the mean of the outcome distribution but left the variance unchanged. In many real applications, treatment affects not only the location but also the *shape* of the outcome distribution. A drug might reduce average blood pressure (a location shift) while also reducing the variability of blood pressure readings (a scale change). A job training program might have a modest average effect but dramatically reduce the probability of zero earnings (a distributional change concentrated in the lower tail). To demonstrate that GBC recovers these richer treatment effects, we design a simulation where the true treatment effect varies across the outcome distribution.\n\nWe generate data with $n = 2000$ observations where the treatment shifts the mean by an amount that depends on $X_0$, and also changes the conditional variance of the outcome. Specifically, the treated outcome has higher variance for units with large $X_0$, creating a QTE curve that varies with the quantile level even after conditioning on covariates.\n\n::: {#144af22e .cell execution_count=11}\n``` {.python .cell-code code-fold=\"false\"}\nimport numpy as np\nimport torch\nimport torch.nn as nn\nnp.random.seed(123)\ntorch.manual_seed(123)\n\nn_dist = 2000\np_dist = 2\n\n# Covariates\nX_dist = np.random.uniform(0, 2, size=(n_dist, p_dist))\n\n# Propensity: moderate confounding\ne_dist = 1 / (1 + np.exp(-1.5 * (X_dist[:, 0] - 1)))\nZ_dist = np.random.binomial(1, e_dist)\n\n# True CATE (mean shift): depends on X_0\ntrue_cate_dist = 2.0 * X_dist[:, 0]\n\n# Control outcomes: fixed variance\nmu0_dist = 3 * X_dist[:, 0] + X_dist[:, 1]\neps0 = np.random.normal(0, 1, n_dist)\nY0_dist = mu0_dist + eps0\n\n# Treated outcomes: mean shift + variance that grows with X_0\neps1 = np.random.normal(0, 1, n_dist)\nsigma_treated = 1.0 + 1.5 * X_dist[:, 0]  # heteroskedastic treated arm\nY1_dist = mu0_dist + true_cate_dist + sigma_treated * eps1\n\nY_dist = Z_dist * Y1_dist + (1 - Z_dist) * Y0_dist\n\n# True QTE at quantile q for covariate x0: shift + scale effect\n# Q_{Y(1)}(q | x) - Q_{Y(0)}(q | x) = cate(x) + (sigma_treated - 1) * Phi^{-1}(q)\nfrom scipy.stats import norm\nq_grid_fine = np.linspace(0.05, 0.95, 50)\n\n# For x0 = 0.5: cate = 1.0, sigma_1 = 1.75, scale_diff = 0.75\nqte_x0_low = 2.0 * 0.5 + (1.0 + 1.5 * 0.5 - 1.0) * norm.ppf(q_grid_fine)\n# For x0 = 1.5: cate = 3.0, sigma_1 = 3.25, scale_diff = 2.25\nqte_x0_high = 2.0 * 1.5 + (1.0 + 1.5 * 1.5 - 1.0) * norm.ppf(q_grid_fine)\n\nprint(f\"True ATE: {true_cate_dist.mean():.3f}\")\nprint(f\"True CATE at x0=0.5: {2.0 * 0.5:.1f}, QTE range: [{qte_x0_low.min():.2f}, {qte_x0_low.max():.2f}]\")\nprint(f\"True CATE at x0=1.5: {2.0 * 1.5:.1f}, QTE range: [{qte_x0_high.min():.2f}, {qte_x0_high.max():.2f}]\")\n```\n:::\n\n\nThe key feature of this design is that the true QTE at quantile level $q$ for a unit with covariate $X_0 = x_0$ is\n$$\n\\text{QTE}(q, x_0) = 2 x_0 + 1.5 x_0 \\cdot \\Phi^{-1}(q),\n$$ {#eq-true-qte-dist}\nwhere $\\Phi^{-1}$ is the standard normal quantile function. The first term is the mean shift (the CATE), and the second term captures the variance effect. At $q = 0.5$, $\\Phi^{-1}(0.5) = 0$, so the QTE at the median equals the CATE. At $q = 0.1$, $\\Phi^{-1}(0.1) \\approx -1.28$, so the QTE is *below* the CATE, the treatment makes the lower tail worse relative to a pure location shift. At $q = 0.9$, the QTE is above the CATE. This V-shaped QTE profile around the CATE is the signature of a variance-increasing treatment, and it is invisible to any method that estimates only the conditional mean.\n\n::: {#cell-fig-true-qte-dist .cell execution_count=12}\n``` {.python .cell-code code-fold=\"true\"}\nimport matplotlib.pyplot as plt\n\nfig, ax = plt.subplots(1, 1, figsize=(7, 4))\nax.plot(q_grid_fine, qte_x0_low, 'b-', linewidth=2, label=r'$X_0 = 0.5$ (true QTE)')\nax.plot(q_grid_fine, qte_x0_high, 'r-', linewidth=2, label=r'$X_0 = 1.5$ (true QTE)')\nax.axhline(y=1.0, color='b', linestyle='--', alpha=0.5, label=r'CATE at $X_0 = 0.5$')\nax.axhline(y=3.0, color='r', linestyle='--', alpha=0.5, label=r'CATE at $X_0 = 1.5$')\nax.set_xlabel('Quantile level $q$')\nax.set_ylabel('QTE$(q, x_0)$')\nax.set_title('True Quantile Treatment Effects with Variance Heterogeneity')\nax.legend(fontsize=8)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![True quantile treatment effects for units with low ($X_0 = 0.5$) and high ($X_0 = 1.5$) covariate values. The treatment shifts both the mean and the variance of the outcome. At higher $X_0$, the variance effect is larger, producing a steeper QTE curve. The dashed horizontal lines show the CATE (the mean of each QTE curve), which captures only the location shift.](ch13-causal_files/figure-html/fig-true-qte-dist-output-1.png){#fig-true-qte-dist width=660 height=372}\n:::\n:::\n\n\n@fig-true-qte-dist reveals the full story that the CATE alone cannot tell. For a unit with $X_0 = 1.5$, the CATE of 3.0 is a reasonable summary of the location shift, but it conceals the fact that the treatment dramatically increases outcome variability. At the 10th percentile, the treatment effect is only about $-0.7$, the treatment actually *worsens* outcomes for the unluckiest individuals. At the 90th percentile, the effect is around $6.7$, nearly twice the CATE. A policymaker who cares about protecting the worst-off would view this treatment very differently from one who cares only about the average. The CATE, by construction, is silent on this distinction.\n\nThis simulation illustrates a general principle: whenever a treatment changes both the location and the scale (or shape) of the conditional outcome distribution, the QTE curve will be non-constant across quantile levels. A flat QTE curve indicates a pure location shift, the treatment moves the entire distribution by the same amount. A positively sloped QTE curve (increasing in $q$) indicates that the treatment increases the spread of outcomes, as in our design. A negatively sloped QTE curve indicates that the treatment *compresses* the outcome distribution, reducing variability. In medical applications, a treatment that reduces both the average severity of symptoms and the variability of outcomes would produce a negatively sloped QTE curve, precisely the kind of treatment that clinicians value most, because it is both effective on average and reliable across patients.\n\nDML and BCF would report the CATE of 1.0 and 3.0 for the two covariate values, correctly capturing the mean shift. But they would miss the variance effect entirely. Neither method has a mechanism for detecting that the treatment increases outcome variability, because they model only the conditional mean of the outcome. GBC, by learning the full conditional quantile function, automatically captures both location and scale effects in a single trained model.\n\n\n## Distributional Treatment Effects {#sec-causal-distributional}\n\nThe QTE profile $\\text{QTE}(q, x)$ provides a function-valued summary of how treatment reshapes the outcome distribution at each covariate value. But sometimes we want a single scalar that captures how *different* the treated and control distributions are, going beyond the comparison of matched quantiles.\n\nThe natural tool for this comparison is the *Wasserstein distance* from optimal transport theory. The $p$-Wasserstein distance between two distributions $P$ and $Q$ on $\\mathbb{R}$ is\n$$\nW_p(P, Q) = \\left( \\inf_{\\gamma \\in \\Gamma(P, Q)} \\int |x - y|^p \\, d\\gamma(x, y) \\right)^{1/p},\n$$ {#eq-wasserstein}\nwhere $\\Gamma(P, Q)$ is the set of all joint distributions (couplings) with marginals $P$ and $Q$. For distributions on the real line, the Wasserstein distance has a closed-form expression in terms of quantile functions:\n$$\nW_p(P, Q) = \\left( \\int_0^1 |Q_P(q) - Q_Q(q)|^p \\, dq \\right)^{1/p}.\n$$ {#eq-wasserstein-quantile}\nThis is a direct consequence of the optimality of the comonotone coupling in one dimension [@villani2009optimal].\n\nFor causal inference, we define the *conditional distributional treatment effect* (CDTE) at covariate value $x$ as\n$$\n\\text{CDTE}(x) = W_2(F_{Y(1) \\mid x}, F_{Y(0) \\mid x}) = \\left( \\int_0^1 \\text{QTE}(q, x)^2 \\, dq \\right)^{1/2}.\n$$ {#eq-cdte}\nThe CDTE measures the total distributional shift induced by the treatment, capturing both location and scale changes in a single number. Notice that $\\text{CDTE}(x)^2 = \\text{CATE}(x)^2 + \\text{Var}_q[\\text{QTE}(q, x)]$ by the bias-variance decomposition: the squared Wasserstein distance decomposes into the squared mean shift (the CATE) plus the variance of the QTE across quantile levels, where the variance is computed with respect to the uniform measure on $[0,1]$: $\\text{Var}_q[\\text{QTE}] = \\int_0^1 \\text{QTE}(q,x)^2 \\, dq - \\left(\\int_0^1 \\text{QTE}(q,x) \\, dq\\right)^2$. When the treatment is a pure location shift ($\\text{QTE}(q, x) = \\text{CATE}(x)$ for all $q$), the variance term vanishes and $\\text{CDTE}(x) = |\\text{CATE}(x)|$. When the treatment also changes the shape of the distribution, the CDTE exceeds $|\\text{CATE}(x)|$ by an amount that reflects the magnitude of the distributional distortion.\n\nThe decomposition $\\text{CDTE}^2 = \\text{CATE}^2 + \\text{Var}_q[\\text{QTE}]$ provides a natural diagnostic for whether CATE-based methods are sufficient. If the ratio $\\text{Var}_q[\\text{QTE}] / \\text{CDTE}^2$ is small across the covariate space, then the treatment is approximately a location shift, and CATE-based methods like DML and BCF capture most of the treatment effect. If the ratio is large, distributional methods like GBC provide strictly more information.\n\nThe GBC framework computes the CDTE at no additional cost beyond training the IQN. Given the trained quantile function $\\hat{Q}(q, \\tilde{x}, z)$, we estimate\n$$\n\\widehat{\\text{CDTE}}(x) = \\left( \\frac{1}{|\\mathcal{U}|} \\sum_{q \\in \\mathcal{U}} \\widehat{\\text{QTE}}(q, x)^2 \\right)^{1/2},\n$$\nwhere $\\mathcal{U}$ is a grid of quantile levels. The *average distributional treatment effect* (ADTE) aggregates over the population: $\\text{ADTE} = E_X[\\text{CDTE}(X)]$. When the ADTE substantially exceeds the $|\\text{ATE}|$, we know that the treatment has important distributional consequences beyond the mean shift. This diagnostic is unique to GBC among the three methods we compare: DML cannot compute it because it estimates only the conditional mean, and BCF provides posterior distributions over the mean treatment effect but not over the quantile treatment effect.\n\nThe connection to optimal transport runs deeper than notation. The quantile function learned by the IQN is precisely a transport map from $\\text{Uniform}(0,1)$ to the conditional outcome distribution. The difference of two such maps, the QTE, describes how to *transport* the control distribution into the treated distribution. In one dimension, this transport map is unique and given by $T(y) = Q_{Y(1) \\mid x}(F_{Y(0) \\mid x}(y))$, which pushes each control outcome to its corresponding treated outcome through quantile matching. The Wasserstein distance is the cost of this transport under quadratic cost, and the GBC framework computes it as a by-product of the quantile function evaluation.\n\nThis optimal transport perspective also connects GBC to the growing literature on counterfactual distributions in economics [@chernozhukov2013inference]. The counterfactual distribution, \"what would the wage distribution look like if we applied the returns structure of group A to the covariate distribution of group B?\", is precisely the pushforward of one distribution through the transport map learned by the other group's quantile function. GBC provides these counterfactual distributions as a direct output, enabling decompositions of distributional differences into composition effects (different covariates) and structural effects (different quantile functions) in the tradition of @machado2005counterfactual.\n\n\n## Exercises {#sec-causal-exercises}\n\nThe first four exercises focus on the mechanics of causal estimation:\npropensity weighting, quantile treatment effects, sensitivity analysis,\nand empirical benchmarking on the LaLonde data.\nThe last four exercises explore distributional treatment effects,\nDML implementation, rank preservation, and risk-sensitive\ntreatment assignment.\n\n::: {#exr-causal-ipw}\n**IPW Estimator.**\nConsider the IPW estimator for the ATE:\n$$\n\\hat{\\tau}_{\\text{IPW}} = \\frac{1}{n} \\sum_{i=1}^n \\left[ \\frac{Z_i Y_i}{\\hat{e}(X_i)} - \\frac{(1-Z_i) Y_i}{1 - \\hat{e}(X_i)} \\right].\n$$\n(a) Show that $E[\\hat{\\tau}_{\\text{IPW}}] = \\tau_0$ under unconfoundedness and correct propensity specification.\n(b) Using the simulation from @sec-causal-simulation, compute the IPW estimator with the true propensity scores $e(X_i)$ and with the estimated $\\hat{e}(X_i)$. Compare the variance of the two estimators.\n(c) What happens to the IPW estimator when $e(X_i)$ is very close to 0 or 1? Compute the IPW estimate after trimming observations with $\\hat{e}(X_i) < 0.05$ or $\\hat{e}(X_i) > 0.95$. Compare with the untrimmed estimate.\n:::\n\n::: {#exr-causal-qte}\n**Quantile Treatment Effects.**\nModify the simulation in @sec-causal-simulation so that the treatment affects not only the mean but also the variance of the outcome:\n$$\nY_i(1) = \\mu_0(X_i) + \\tau(X_i) + (1 + 0.5 X_{i,0}) \\cdot \\varepsilon_i, \\quad Y_i(0) = \\mu_0(X_i) + \\varepsilon_i,\n$$\nwhere $\\varepsilon_i \\sim N(0, 1)$. In this design, the treatment increases the spread of outcomes for units with large $X_0$.\n(a) Train a GBC model and plot the QTE profile $\\widehat{\\text{QTE}}(q)$ for individuals with $X_0 = 0.5$ and $X_0 = 1.5$. How do they differ?\n(b) Compute the CATE from the QTE by integration. Verify that it matches the direct mean-based CATE.\n(c) Can DML or BCF detect the variance effect? Explain why or why not.\n:::\n\n::: {#exr-causal-propensity}\n**Propensity Score Sensitivity.**\nUsing the simulation design from @sec-causal-simulation:\n(a) Estimate the propensity score using three methods: (i) logistic regression, (ii) a neural network with one hidden layer, and (iii) a neural network with three hidden layers. For each, compute the CATE RMSE of the downstream GBC model.\n(b) Deliberately misspecify the propensity model by omitting $X_1$ from the inputs. How does this affect the CATE estimates? Does the GBC model partially compensate for the misspecification through the outcome model?\n(c) The semiparametric efficiency result (Proposition 13.1) requires the product of the propensity and outcome convergence rates to be $o(n^{-1/2})$. Generate data with $n = 200, 500, 1000, 2000$ and plot the CATE RMSE as a function of $n$ for the correctly specified and misspecified propensity models. At what sample size does the misspecification penalty become negligible?\n:::\n\n::: {#exr-causal-lalonde}\n**LaLonde Extensions.**\nThe LaLonde dataset from @sec-causal-lalonde can be accessed via the `causalml` Python package or downloaded from the Dehejia--Wahba webpage.\n(a) Implement the GBC causal model from Algorithm 13.1 on the LaLonde data. Use log-transformed earnings $\\log(\\text{re78} + 1)$ as the outcome. Report the ATE, a 95% quantile interval, and the QTE profile.\n(b) Conduct a *placebo test*: use pre-treatment earnings $\\text{re74}$ as the outcome variable. Since the training program had not yet begun, the treatment effect should be approximately zero. Does your GBC model correctly find a null effect?\n(c) Compute individual-level CATE estimates and identify the subgroup that benefits most from the program. Which covariates are most predictive of large treatment effects?\n:::\n\n::: {#exr-causal-wasserstein}\n**Distributional Treatment Effects.**\nUsing the simulation from @sec-causal-dist-sim with heteroskedastic treatment effects:\n(a) Compute the estimated CDTE $\\widehat{\\text{CDTE}}(x)$ for each unit using the trained GBC model from @sec-causal-simulation. Plot the CDTE against the absolute CATE. For which units does the CDTE substantially exceed $|\\text{CATE}|$? Relate this to the variance heterogeneity in the data-generating process.\n(b) Compute the Wasserstein-2 distance between the treated and control outcome distributions using the quantile formula (@eq-wasserstein-quantile) and a grid of 100 quantile levels. Compare with a naive estimate that computes $|\\bar{Y}_{\\text{treated}} - \\bar{Y}_{\\text{control}}|$ (the absolute difference in means). By how much does the Wasserstein distance exceed the mean difference?\n(c) The decomposition $\\text{CDTE}^2 = \\text{CATE}^2 + \\text{Var}_q[\\text{QTE}]$ allows us to measure the fraction of the distributional effect attributable to scale changes rather than location shifts. Compute this fraction for units at $X_0 = 0.5$ and $X_0 = 1.5$. At which covariate value is the scale effect more important relative to the location effect?\n:::\n\n::: {#exr-causal-dml-compare}\n**DML Two-Stage Procedure.**\nImplement the DML partially linear regression model from scratch (without using the `doubleml` package) on the simulation from @sec-causal-simulation.\n(a) In the first stage, fit a random forest to predict $Y$ from $X$ (the outcome nuisance function $\\hat{g}$) and another random forest to predict $Z$ from $X$ (the propensity nuisance function $\\hat{m}$). Use 5-fold cross-fitting: for each fold, train on the other 4 folds and predict on the held-out fold. Compute the outcome residuals $\\tilde{Y}_i = Y_i - \\hat{g}(X_i)$ and the treatment residuals $\\tilde{Z}_i = Z_i - \\hat{m}(X_i)$.\n(b) In the second stage, regress $\\tilde{Y}$ on $\\tilde{Z}$ using OLS to obtain $\\hat{\\theta}_{\\text{DML}}$. Report the point estimate and its standard error. Compare with the true ATE. Explain why the PLR specification yields a biased estimate under the nonlinear CATE design.\n(c) Now implement DML's interactive regression model (IRM) by estimating $\\hat{\\mu}(x, z) = \\hat{E}[Y \\mid X = x, Z = z]$ separately for $z = 0$ and $z = 1$ using random forests. Compute the CATE as $\\hat{\\tau}_{\\text{IRM}}(x) = \\hat{\\mu}(x, 1) - \\hat{\\mu}(x, 0)$. How does the IRM CATE RMSE compare with GBC's?\n:::\n\n::: {#exr-causal-rank}\n**Rank Preservation and QTE Interpretation.**\nThe interpretive caveat in @sec-causal-cate warns that $\\text{QTE}(q, x) \\neq Q_{Y(1) - Y(0)}(q \\mid x)$ in general. This exercise explores when the two quantities coincide and what happens when they diverge.\n(a) Generate data under *rank preservation*: for each unit, draw a single $\\varepsilon_i \\sim N(0,1)$ and set $Y_i(0) = \\mu_0(X_i) + \\varepsilon_i$ and $Y_i(1) = \\mu_0(X_i) + \\tau(X_i) + \\varepsilon_i$. Under this design, the rank of unit $i$ in the control distribution is the same as its rank in the treated distribution. Verify numerically that $\\text{QTE}(q, x) = Q_{Y(1) - Y(0)}(q \\mid x) = \\tau(x)$ for all $q$ (i.e., the QTE is flat and equals the CATE).\n(b) Now break rank preservation: set $Y_i(1) = \\mu_0(X_i) + \\tau(X_i) + (1 + X_{i,0}) \\varepsilon_i'$ where $\\varepsilon_i'$ is drawn *independently* of $\\varepsilon_i$. Compute both $\\text{QTE}(q, x)$ and $Q_{Y(1) - Y(0)}(q \\mid x)$ from the population distributions. Plot both curves and show that they differ.\n(c) In practice, we never observe both potential outcomes, so we cannot distinguish between rank preservation and rank reversal from data alone. Discuss the implications for interpreting QTE estimates in a policy context: what can a policymaker conclude from a QTE profile, and what requires additional assumptions?\n:::\n\n::: {#exr-causal-cvar}\n**Risk-Sensitive Treatment Assignment.**\nThe connection between GBC and Yaari's dual theory (@sec-causal-distributional) suggests that risk-averse policymakers should evaluate treatments using distorted expectations rather than the standard ATE.\n(a) Using the trained GBC model from @sec-causal-simulation, compute the CVaR-based treatment effect at level $\\eta = 0.2$: average the QTE over only the bottom 20% of quantile levels, $\\widehat{\\text{QTE}}_{\\text{CVaR}} = 5 \\int_0^{0.2} \\widehat{\\text{QTE}}(q, x) \\, dq$. Compare this with the standard CATE (the average over all quantile levels). For which covariate values does the CVaR treatment effect differ most from the CATE?\n(b) Design a treatment assignment policy that maximizes the CVaR-based welfare: assign treatment to units where $\\widehat{\\text{QTE}}_{\\text{CVaR}}(x) > 0$ (the treatment improves the worst outcomes). Compare this policy with the standard policy that assigns treatment where $\\hat{\\tau}(x) > 0$ (the CATE is positive). What fraction of units receive different assignments under the two policies?\n(c) Compute the population welfare under both policies using the true potential outcomes. Which policy achieves higher average welfare? Which achieves higher welfare for the bottom 20% of outcomes? Discuss the equity-efficiency tradeoff.\n:::\n\n",
    "supporting": [
      "ch13-causal_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}