{
  "hash": "1add4ad30858a934259b5928f55bc52b",
  "result": {
    "engine": "jupyter",
    "markdown": "# Boundary Augmentation for Jump Processes {#sec-jumps}\n\nWhat happens when the response surface is *not* smooth, when it contains sharp jump discontinuities?\n\nJump discontinuities arise naturally in computer experiments. A semiconductor fabrication simulator may predict smooth transport times until the system hits a capacity threshold, at which point queuing effects cause the response to jump [@kang2024bayesian]. Aerodynamic simulators produce smooth coefficients except near the sound barrier, where shock waves create abrupt regime changes. Phase transitions, structural failure boundaries, and manufacturing tolerance limits all produce response surfaces where the function value changes abruptly across a boundary in input space.\n\nThese problems are common enough that an entire sub-literature of Gaussian process methods has developed to handle them: treed GPs [@gramacy2008bayesian], bi-mixture GPs [@park2026active], and most recently the modular jump GP (MJGP) of @flowers2026modular, which combines EM clustering with a jump-aware GP. GBC can handle jump discontinuities more effectively than any of these methods, using a simple three-step augmentation strategy that we call **Aug-IQN**.\n\nThe idea is to separate the problem into two parts: (i) detecting *which side of the jump boundary* each point lies on, and (ii) learning the conditional quantile function *given* this regime information. Step (i) is a classification problem; step (ii) is the standard IQN problem from @sec-iqn, but with an extra input feature encoding the regime.\n\nThe chapter proceeds as follows. We first formalize the jump discontinuity problem and explain why both GPs and plain IQNs struggle with it (@sec-jumps-problem). We then develop the three steps of the Aug-IQN pipeline: EM clustering to infer regime labels (@sec-jumps-em), MLP classification to predict regimes from inputs alone (@sec-jumps-classifier), and feature augmentation to provide regime information to the IQN (@sec-jumps-augiqn). We evaluate Aug-IQN on three benchmark datasets, Phantom (@sec-jumps-phantom), Star (@sec-jumps-star), and AMHV (@sec-jumps-amhv), and show that GBC outperforms the specialized MJGP method on all three, Aug-IQN on Phantom and Star, and plain IQN on AMHV, where the smooth boundary makes augmentation unnecessary. We then extend the pipeline to three or more regimes (@sec-jumps-three-regimes), compare to other jump methods in the literature (@sec-jumps-comparison), and provide practical guidance on when augmentation helps (@sec-jumps-when).\n\n\n## The Jump Discontinuity Problem {#sec-jumps-problem}\n\nThe difficulty is not the discontinuity per se, after all, a lookup table could handle a known partition perfectly. The difficulty is that the boundary between regimes is unknown, must be inferred from noisy data, and may have complex geometry.\n\nConsider a response surface of the form\n$$\nf(x) = f_1(x) \\cdot \\mathbf{1}_{R_1}(x) + f_2(x) \\cdot \\mathbf{1}_{R_2}(x),\n$$ {#eq-jump-surface}\nwhere $R_1$ and $R_2$ partition the input space $\\mathcal{X}$ into two regions separated by a boundary $\\partial B$, and $f_1, f_2$ are smooth functions with $f_1(x) \\neq f_2(x)$ for $x$ near $\\partial B$. Observations are noisy:\n$$\ny_i = f(x_i) + \\varepsilon_i, \\quad \\varepsilon_i \\sim \\mathcal{N}(0, \\sigma^2).\n$$\n\nThe difficulty is at the boundary. Within each region, $f$ is smooth and any reasonable regression method will perform well. The problem is that points near $\\partial B$ on different sides have similar inputs $x$ but very different responses $y$. A method that pools information across the boundary, as any smooth interpolator must, will blur the jump. The magnitude of the blurring depends on both the method's smoothing bandwidth and the jump size $|f_1(x) - f_2(x)|$ at the boundary. For a jump of size $\\Delta$ and a method with effective smoothing radius $h$, the blurring region has width approximately $2h$ and the prediction error within this region is of order $\\Delta/2$, half the jump size. This is a substantial error that dominates the overall RMSE and CRPS whenever the boundary has non-trivial length in the input domain.\n\n*Why GPs struggle.* A stationary GP with kernel $k(x, x') = k(\\|x - x'\\|)$ assigns positive covariance to any two points that are close in input space. Near the boundary, the GP averages responses from both regimes, producing blurred mean predictions that overshoot on one side and undershoot on the other. At the same time, the GP interprets the disagreement between regimes as noise, producing inflated uncertainty and overly wide prediction intervals everywhere near the boundary. Underlying both problems is a single length-scale compromise: a short length scale captures the jump but underfits the smooth regions, while a long one fits the smooth regions but blurs the jump.\n\n*Why plain IQN also struggles.* Perhaps surprisingly, a standard IQN (@sec-iqn) also has difficulty with sharp jumps, though for a different reason. The IQN's composite loss (@sec-iqn-loss) includes an $L_1$ location-anchor term that encourages the network to predict the conditional median. Near the jump boundary, the conditional median is a weighted average of the two regimes, exactly the blurred prediction we want to avoid.\n\nReducing the anchor weight helps. With the *pinball-dominant* loss configuration $(w_1, w_2, w_3) = (0.10, 0.20, 0.70)$, the IQN is freer to learn sharp transitions because the $L_1$ term no longer dominates the gradient near the boundary. On the Phantom benchmark (which we will discuss in @sec-jumps-phantom), this loss reweighting alone improves CRPS from 0.039 to 0.031, a 20% gain with no architectural change. But CRPS = 0.031 is still three times worse than the specialized MJGP method's 0.010. The loss-weight trick helps but does not solve the fundamental problem.\n\nThe IQN must simultaneously learn two things: the geometry of the jump boundary (a classification problem) and the quantile function on each side (a regression problem). Asking a single network to do both is feasible in principle, neural networks are universal approximators [@hornik1989multilayer], but in practice it is inefficient. The boundary geometry is a hard combinatorial structure that gradient-based optimization discovers slowly.\n\n*The augmentation idea.* The solution is to separate the two tasks. If we could tell the IQN which regime each point belongs to, it would only need to learn the (smooth) quantile functions on each side, a much easier problem. We cannot observe regime labels directly, but we can *infer* them from the data and provide them as an additional input feature. This is the Aug-IQN pipeline:\n\n1. *Cluster* the response values to infer regime labels.\n2. *Classify* the inputs to predict regime membership.\n3. *Augment* the IQN's input with the classifier's prediction.\n\nEach step is simple and uses standard tools; the power comes from the composition.\n\nWe can formalize the augmentation idea as follows. Define the augmentation map $T: \\mathcal{X} \\to \\mathcal{X} \\times [0,1]$ by $T(x) = [x, \\hat{f}(x)]$, where $\\hat{f}$ is a learned classifier. Then Aug-IQN trains an IQN on the augmented space, learning the quantile function $G_\\phi(\\tau, T(x))$ instead of $G_\\phi(\\tau, x)$. This is a special case of the GBC framework from @sec-iqn, only the input representation changes, not the architecture or the loss.\n\nThe augmentation map $T$ is reminiscent of feature engineering in classical\nmachine learning: we are adding a derived feature that encodes domain\nknowledge (in this case, knowledge about the jump structure inferred\nfrom the data). The difference from traditional feature engineering is\nthat $T$ is itself *learned* from the data, we do not need to know\nthe boundary geometry in advance. The EM + classifier pipeline discovers\nthe boundary automatically, and the augmented feature communicates\nthis discovery to the IQN.\n\nThe next three sections develop each step of the pipeline in detail.\n\n\n## EM Clustering {#sec-jumps-em}\n\nThe first step in the Aug-IQN pipeline is to determine which regime each training point belongs to. Since the response surface has a jump, the marginal distribution of $\\{y_i\\}$ is bimodal: one mode for each regime. We can recover the regime labels by fitting a two-component Gaussian mixture model via the Expectation-Maximization (EM) algorithm.\n\nA two-component Gaussian mixture models the response as\n$$\np(y) = \\pi_1 \\, \\mathcal{N}(y \\mid \\mu_1, \\sigma_1^2) + \\pi_2 \\, \\mathcal{N}(y \\mid \\mu_2, \\sigma_2^2),\n$$ {#eq-gmm}\nwhere $\\pi_1 + \\pi_2 = 1$ are the mixing weights and $(\\mu_k, \\sigma_k^2)$ are the mean and variance of component $k$. The EM algorithm alternates between computing posterior responsibilities $\\gamma_{ik} = P(z_i = k \\mid y_i)$ (E-step) and updating the parameters to maximize the expected complete-data log-likelihood (M-step). After convergence, we assign hard labels:\n$$\nc_i = \\arg\\max_k \\; \\gamma_{ik} \\in \\{0, 1\\}.\n$$\n\nFor jump discontinuities with well-separated regimes, the marginal distribution of $y$ has two clearly separated modes, and EM reliably identifies them even without any information about the inputs $x$. The requirement is that the *jump magnitude* (the difference $|\\mu_1 - \\mu_2|$) is large relative to the within-regime noise $\\sigma_k$. More precisely, the signal-to-noise ratio for clustering is $\\mathrm{SNR} = |\\mu_1 - \\mu_2| / \\sqrt{(\\sigma_1^2 + \\sigma_2^2)/2}$. When $\\mathrm{SNR} \\gg 1$, the two Gaussian components are well-separated and EM converges quickly to labels that agree with the true regime assignments. When $\\mathrm{SNR} \\approx 1$, the components overlap substantially and EM's label accuracy degrades. A useful rule of thumb, which we verify empirically in @exr-em-overlap, is that EM clustering achieves $> 90\\%$ accuracy when $\\mathrm{SNR} > 2$ and $> 99\\%$ accuracy when $\\mathrm{SNR} > 4$.\n\nConvergence of the EM algorithm is guaranteed to a local maximum of the marginal likelihood, but the algorithm may converge to a spurious solution if initialized poorly. For the two-component case with well-separated modes, standard random initialization or $k$-means initialization (the default in scikit-learn) is sufficient. In our experiments across hundreds of replicates, we never observed EM converging to a degenerate solution on datasets with $\\mathrm{SNR} > 3$.\n\nThe Phantom and Star datasets from @flowers2026modular satisfy this condition: the two regimes are generated from Gaussian components with well-separated means, producing a strongly bimodal marginal. On these datasets, EM clustering achieves near-perfect label recovery, over 99% of points are assigned to the correct regime.\n\nWhen does this fail? If the two regimes overlap substantially in the marginal distribution, for instance, when the jump magnitude is small relative to the noise, or when the within-regime variability spans a range that covers both modes, EM will misassign labels near the overlap. The AMHV semiconductor dataset (@sec-jumps-amhv) illustrates this: the two response regimes overlap, making EM clustering unreliable. In such cases, the augmentation step is unnecessary and potentially harmful, so we use plain GBC instead.\n\nThe implementation is straightforward using scikit-learn's `GaussianMixture`:\n\n::: {.cell execution_count=2}\n``` {.python .cell-code code-fold=\"false\"}\nimport numpy as np\nfrom sklearn.mixture import GaussianMixture\n\ndef cluster_responses(y, n_components=2, seed=0):\n    \"\"\"Cluster response values into regimes using EM.\n\n    Args:\n        y: (n,) array of response values\n        n_components: number of mixture components\n        seed: random seed for reproducibility\n\n    Returns:\n        labels: (n,) binary array of regime labels\n    \"\"\"\n    gm = GaussianMixture(n_components=n_components, random_state=seed)\n    gm.fit(y.reshape(-1, 1))\n    labels = gm.predict(y.reshape(-1, 1))\n    # Convention: label 0 = lower-mean regime\n    if gm.means_[0, 0] > gm.means_[1, 0]:\n        labels = 1 - labels\n    return labels\n```\n:::\n\n\nLet us see this in action on a synthetic example with a jump at $x = 0.5$:\n\n::: {.cell execution_count=3}\n``` {.python .cell-code code-fold=\"true\"}\nimport matplotlib.pyplot as plt\n\nnp.random.seed(42)\nn = 500\nx = np.random.uniform(0, 1, n)\n# Jump at x = 0.5: regime 0 has mean 0, regime 1 has mean 3\ntrue_regime = (x > 0.5).astype(int)\ny = np.where(true_regime == 0,\n             np.sin(2 * np.pi * x) + 0.2 * np.random.randn(n),\n             3.0 + 0.5 * np.cos(2 * np.pi * x) + 0.2 * np.random.randn(n))\n\nlabels = cluster_responses(y)\naccuracy = np.mean(labels == true_regime)\n\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 3.5))\n\n# Left: response histogram\nax1.hist(y[labels == 0], bins=30, alpha=0.6, color='steelblue', label='Regime 0', density=True)\nax1.hist(y[labels == 1], bins=30, alpha=0.6, color='coral', label='Regime 1', density=True)\nax1.set_xlabel(\"Response y\")\nax1.set_ylabel(\"Density\")\nax1.set_title(f\"EM clustering (accuracy: {accuracy:.1%})\")\nax1.legend(fontsize=8)\n\n# Right: labeled scatter\nax2.scatter(x[labels == 0], y[labels == 0], s=8, alpha=0.5, color='steelblue', label='Regime 0')\nax2.scatter(x[labels == 1], y[labels == 1], s=8, alpha=0.5, color='coral', label='Regime 1')\nax2.axvline(0.5, color='k', linestyle='--', linewidth=1, alpha=0.5, label='True boundary')\nax2.set_xlabel(\"x\")\nax2.set_ylabel(\"y\")\nax2.set_title(\"Labeled training data\")\nax2.legend(fontsize=8)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![EM clustering recovers regime labels from the marginal response distribution. Left: the bimodal response histogram with fitted Gaussian components. Right: the labeled training data in input-output space.](ch08-jumps_files/figure-pdf/fig-em-clustering-output-1.pdf){#fig-em-clustering fig-pos='H'}\n:::\n:::\n\n\nEM clustering uses *only* the response values $y$, it knows nothing about the inputs $x$. Yet the recovered labels almost perfectly separate the two regimes because the jump creates a large separation between the modes of the marginal distribution.\n\nWhy cluster on the response $y$ alone rather than on the joint $(x, y)$ space? Simplicity and robustness. Clustering on $y$ alone works whenever the jump magnitude is large relative to the within-regime variability, regardless of the boundary's geometric complexity. Clustering on $(x, y)$ would require choosing a distance metric that balances input-space proximity against response-space proximity, and the optimal balance depends on the (unknown) boundary geometry. In high dimensions, the curse of dimensionality makes joint clustering unreliable, distances in $\\mathbb{R}^{d+1}$ become increasingly dominated by the $d$-dimensional input component, washing out the response signal. By clustering on $y$ alone, we sidestep these issues entirely. The cost is that EM clustering fails when the marginal response modes overlap, but as we will see in @sec-jumps-amhv, this is exactly the case where augmentation is unnecessary anyway.\n\n::: {.callout-note}\n*Remark.* The EM clustering step is shared with the MJGP method of @flowers2026modular. What differs is what comes *after*: MJGP feeds the labels to a local GP, while Aug-IQN trains a classifier and augments the IQN input. The key insight is that the same preprocessing can be combined with different downstream models.\n:::\n\n\n## MLP Classifier for Regime Detection {#sec-jumps-classifier}\n\nEM clustering gives us regime labels $c_i \\in \\{0, 1\\}$ for the training data, but we also need regime predictions for *new* test points where we observe only $x$, not $y$. The second step of Aug-IQN trains a classifier to predict regime membership from inputs alone:\n$$\n\\hat{f}(x) = P(c = 1 \\mid x) \\in [0, 1].\n$$ {#eq-classifier}\n\nThis is a standard binary classification problem. We use a multi-layer perceptron (MLP) trained with binary cross-entropy (BCE) loss. The choice of classifier is important but not exotic: any classifier that can represent nonlinear decision boundaries will work. We use an MLP because it is a natural companion to the IQN (same optimizer, same framework), but random forests, gradient-boosted trees, or kernel SVMs with RBF kernels could serve the same purpose. The MLP has the advantage of producing calibrated probabilities via the sigmoid output, which gives the IQN a continuous signal about boundary proximity rather than a hard binary label. We will see in @exr-soft-augmentation that this soft augmentation is important for performance near the boundary.\n\nThe classifier is a feedforward network with three hidden layers of 256 units each and ReLU activations. It outputs raw logits; we apply sigmoid at inference time via `predict_prob` for numerical stability (using `BCEWithLogitsLoss` during training):\n\n::: {.cell execution_count=4}\n``` {.python .cell-code code-fold=\"false\"}\nimport torch\nimport torch.nn as nn\n\nclass BoundaryClassifier(nn.Module):\n    \"\"\"MLP classifier for regime detection.\n\n    Args:\n        xdim:     input dimension\n        hdim:     hidden layer width (default 256)\n        n_layers: number of hidden layers (default 3)\n    \"\"\"\n    def __init__(self, xdim, hdim=256, n_layers=3):\n        super().__init__()\n        layers = [nn.Linear(xdim, hdim), nn.ReLU()]\n        for _ in range(n_layers - 1):\n            layers += [nn.Linear(hdim, hdim), nn.ReLU()]\n        layers += [nn.Linear(hdim, 1)]\n        self.net = nn.Sequential(*layers)\n        # Xavier initialization\n        for m in self.modules():\n            if isinstance(m, nn.Linear):\n                nn.init.xavier_uniform_(m.weight)\n                nn.init.zeros_(m.bias)\n\n    def forward(self, x):\n        return self.net(x).squeeze(-1)\n\n    def predict_prob(self, x):\n        \"\"\"Sigmoid applied at inference time for numerical stability.\"\"\"\n        return torch.sigmoid(self.forward(x))\n```\n:::\n\n\nTraining uses Adam with cosine annealing, the same optimizer configuration we use for the IQN itself:\n\n::: {.cell execution_count=5}\n``` {.python .cell-code code-fold=\"false\"}\ndef train_classifier(X_train, labels, hdim=256, n_layers=3,\n                     epochs=3000, lr=1e-3, seed=0):\n    \"\"\"Train boundary classifier.\n\n    Args:\n        X_train: (n, d) input array\n        labels:  (n,) binary regime labels from EM\n        hdim:    hidden dimension\n        n_layers: number of hidden layers\n        epochs:  training epochs\n        lr:      learning rate\n        seed:    random seed\n\n    Returns:\n        clf:     trained classifier\n        x_mean:  input mean (for normalization)\n        x_std:   input std (for normalization)\n        accuracy: training accuracy\n    \"\"\"\n    torch.manual_seed(seed)\n\n    # Normalize inputs\n    x_mean = X_train.mean(0)\n    x_std = X_train.std(0) + 1e-8\n    Xt = torch.tensor((X_train - x_mean) / x_std, dtype=torch.float32)\n    yt = torch.tensor(labels, dtype=torch.float32)\n\n    clf = BoundaryClassifier(X_train.shape[1], hdim=hdim, n_layers=n_layers)\n    opt = torch.optim.Adam(clf.parameters(), lr=lr, weight_decay=1e-4)\n    sched = torch.optim.lr_scheduler.CosineAnnealingLR(\n        opt, T_max=epochs, eta_min=lr * 0.01\n    )\n\n    clf.train()\n    for _ in range(epochs):\n        opt.zero_grad()\n        pred = clf(Xt)\n        loss = nn.functional.binary_cross_entropy_with_logits(pred, yt)\n        loss.backward()\n        opt.step()\n        sched.step()\n\n    clf.eval()\n    with torch.no_grad():\n        accuracy = ((clf.predict_prob(Xt) > 0.5).float() == yt).float().mean().item()\n\n    return clf, x_mean, x_std, accuracy\n```\n:::\n\n\n*Classifier accuracy matters.* The classifier's accuracy is the single most important factor in Aug-IQN performance. If the classifier perfectly identifies the boundary, the IQN receives a clean signal about which regime each point belongs to, and the problem reduces to smooth quantile regression on each side. If the classifier is inaccurate, the augmented feature provides noisy regime information that the IQN must compensate for.\n\nThis dependence was quantified empirically on the Phantom dataset:\n\n| Classifier | Accuracy | CRPS |\n|:--------|:-----:|:----:|\n| SVC (linear) | 82% | 0.024 |\n| MLP 128×2 / 1000 ep | 99.4% | 0.013 |\n| MLP 256×3 / 2000 ep | 99.9% | 0.010 |\n| MLP 256×3 / 3000 ep | 99.98% | 0.009 |\n\n: Classifier accuracy drives Aug-IQN performance. All other hyperparameters held constant. {#tbl-classifier-accuracy}\n\nGoing from 82% to 99.98% accuracy reduces CRPS by a factor of 2.7. The marginal returns diminish, the jump from 99.4% to 99.98% only improves CRPS from 0.013 to 0.009, but even small improvements in classifier accuracy near the boundary translate to meaningful gains in downstream quantile estimation.\n\nThis finding has a practical implication: invest computational budget in the classifier. Training the MLP for 3000 epochs with a width of 256 takes about 5 seconds on a modern GPU. This is a small fraction of the total Aug-IQN training time and yields the largest improvement.\n\n### Sensitivity to Classifier Accuracy {#sec-jumps-classifier-sensitivity}\n\nThe mechanism behind @tbl-classifier-accuracy reveals when misclassification is catastrophic and when it is merely inconvenient.\n\nConsider a point $x_i$ near the jump boundary that truly belongs to regime 0 but is misclassified as regime 1. The IQN receives the augmented input $\\tilde{x}_i = [x_i, \\hat{f}(x_i)]$ with $\\hat{f}(x_i) \\approx 1$, and the training target is $y_i \\sim f_0(x_i) + \\varepsilon_i$, a response from regime 0. From the IQN's perspective, this is a point in regime 1 with an anomalously low (or high) response. If the misclassified point is near the boundary, the IQN can partially absorb the error, because nearby correctly classified points from regime 0 provide a smooth transition in the augmented feature space. The IQN learns that the region $\\hat{f}(x) \\approx 0.5$ is a transition zone where both regimes contribute, and a few misclassified points in this zone merely widen the transition slightly.\n\nThe situation differs for a misclassified point far from the boundary. If $x_i$ is deep inside regime 0 (where $\\hat{f}(x_i)$ should be near 0) but receives $\\hat{f}(x_i) \\approx 1$, the IQN sees a regime-1 point with a regime-0 response at a location where all neighboring points agree on regime 1. This is a genuine outlier in the augmented feature space, and it corrupts the IQN's learned quantile function for regime 1 at that location. Fortunately, such gross misclassifications are rare for any reasonable classifier, because the boundary is where classification is hardest and the interior is where it is easiest.\n\nThis analysis explains the graceful degradation we observe empirically. Going from 99.98% to 99.4% classifier accuracy means roughly 50 additional misclassified points out of 9,000. If most of those 50 points are near the boundary, which they are, because the boundary is where the classifier's sigmoid output is near 0.5 and the decision is hardest, the effect on the IQN is modest: CRPS increases from 0.009 to 0.013, a 44% increase that still leaves Aug-IQN far ahead of plain GBC's 0.031. Going further down to 82% accuracy (an SVC with a linear kernel on the sinusoidal Phantom boundary) means roughly 1,600 misclassified points. At this level, many misclassified points are no longer confined to the boundary neighborhood; they are scattered throughout the domain wherever the linear decision boundary deviates from the true sine curve. The IQN's CRPS rises to 0.024, still better than plain GBC's 0.031, because even a poor classifier provides some boundary information, but no longer competitive with MJGP's 0.010.\n\nThe practical takeaway is that Aug-IQN is robust to small amounts of boundary-localized misclassification but degrades when the classifier makes systematic errors across large regions of input space. This is why we recommend overinvesting in the classifier: a few extra seconds of training buys insurance against the one failure mode that can undermine the entire pipeline.\n\nAn important distinction exists between *random* misclassification (where individual points near the boundary are misassigned due to noise) and *systematic* misclassification (where the classifier's decision boundary deviates from the true boundary over an extended region). The former produces a thin layer of noise near the boundary that the IQN can absorb; the latter produces a coherent error signal that corrupts the IQN's learned quantile function over the entire misclassified region. The SVC's 82% accuracy on Phantom is an example of systematic misclassification: the linear decision boundary misses the sine curve's oscillations, producing long arcs of input space where every point is assigned to the wrong regime.\n\nLet us apply the classifier to our synthetic example:\n\n::: {.cell execution_count=6}\n``` {.python .cell-code code-fold=\"true\"}\n# Train classifier on the synthetic data\nclf, x_mean, x_std, acc = train_classifier(\n    x.reshape(-1, 1), labels, hdim=128, n_layers=2, epochs=2000, seed=42\n)\n\n# Predict on a grid\nx_grid = np.linspace(0, 1, 500).reshape(-1, 1)\nXt_grid = torch.tensor((x_grid - x_mean) / x_std, dtype=torch.float32)\nwith torch.no_grad():\n    prob_grid = clf.predict_prob(Xt_grid).numpy()\n\nfig, ax = plt.subplots(1, 1, figsize=(6, 3.5))\nax.plot(x_grid, prob_grid, color='steelblue', linewidth=2, label=r'$\\hat{f}(x) = P(\\mathrm{regime}=1|x)$')\nax.axvline(0.5, color='k', linestyle='--', linewidth=1, alpha=0.5, label='True boundary')\nax.set_xlabel(\"x\")\nax.set_ylabel(\"Probability\")\nax.set_title(f\"Boundary classifier (accuracy: {acc:.1%})\")\nax.legend(fontsize=8)\nax.set_ylim(-0.05, 1.05)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Learned boundary classifier. The sigmoid output transitions sharply from 0 to 1 near the true boundary at x = 0.5, providing the IQN with a clean regime indicator.](ch08-jumps_files/figure-pdf/fig-classifier-output-output-1.pdf){#fig-classifier-output fig-pos='H'}\n:::\n:::\n\n\n## Feature Augmentation: Aug-IQN {#sec-jumps-augiqn}\n\nThe third and final step is the simplest: append the classifier's output to the IQN's input. If the original input is $x \\in \\mathbb{R}^d$, the augmented input is\n$$\n\\tilde{x} = [x, \\; \\hat{f}(x)] \\in \\mathbb{R}^{d+1},\n$$ {#eq-augmented-input}\nwhere $\\hat{f}(x) = P(c = 1 \\mid x) \\in [0,1]$ is the classifier probability from @eq-classifier. We then train a standard IQN on the augmented data $\\{(\\tilde{x}_i, y_i)\\}_{i=1}^n$ using the pinball-dominant loss $(w_1, w_2, w_3) = (0.10, 0.20, 0.70)$.\n\nThe augmented feature $\\hat{f}(x)$ acts as a *soft boundary indicator*. Points deep inside regime 0 have $\\hat{f}(x) \\approx 0$; points deep inside regime 1 have $\\hat{f}(x) \\approx 1$; points near the boundary have $\\hat{f}(x) \\approx 0.5$. The augmented feature carries information that is not available in the original input $x$ alone: it tells the IQN which regime the point likely belongs to. Without this feature, the IQN must infer the regime from the spatial pattern of nearby training points, a task that becomes harder as the boundary geometry becomes more complex.\n\nWithout augmentation, the IQN must discover the jump boundary from the input-output relationship alone, a hard problem because the boundary geometry can be arbitrarily complex (sinusoidal, star-shaped, etc.). With augmentation, the IQN can learn a simple rule: \"if $\\hat{f}(x) < 0.5$, predict the low-regime quantile function; if $\\hat{f}(x) > 0.5$, predict the high-regime quantile function; near 0.5, interpolate.\" The actual response surface within each regime is smooth, so the IQN's standard architecture handles it easily.\n\nThe central idea is *boundary information as a feature, not a constraint*. The MJGP method of @flowers2026modular also detects the boundary (using the same EM + classifier pipeline), but then uses it to partition the data and fit separate local GPs in each region. Aug-IQN takes a simpler approach: it provides the boundary information as an input and lets the IQN figure out how to use it. This avoids the need for separate models, explicit partitioning logic, and the cubic-cost GP inference on each partition.\n\nThe full Aug-IQN pipeline is summarized in the following algorithm.\n\n::: {.callout-note appearance=\"minimal\"}\n**Algorithm: Aug-IQN (Boundary-Augmented Implicit Quantile Network)**\n\n- **Input:** Training data $\\{(x_i, y_i)\\}_{i=1}^n$, test inputs $\\{x_j^*\\}_{j=1}^m$\n- **Step 1 (EM Clustering):** Fit a two-component GMM to $\\{y_i\\}$. Assign hard labels $c_i = \\arg\\max_k \\gamma_{ik}$.\n- **Step 2 (Classify):** Train MLP classifier $\\hat{f}: \\mathcal{X} \\to [0,1]$ on $\\{(x_i, c_i)\\}$ via BCE loss.\n- **Step 3 (Augment + Train):** Form augmented inputs $\\tilde{x}_i = [x_i, \\hat{f}(x_i)]$. Train IQN on $\\{(\\tilde{x}_i, y_i)\\}$ with pinball-dominant loss $(0.10, 0.20, 0.70)$.\n- **Predict:** For each test input $x_j^*$, compute $\\tilde{x}_j^* = [x_j^*, \\hat{f}(x_j^*)]$ and draw quantile samples $\\hat{y}^{(b)} = G_\\phi(\\tau^{(b)}, \\tilde{x}_j^*)$, $\\tau^{(b)} \\sim U(0,1)$.\n- **Output:** Posterior quantile samples for each test input.\n:::\n\nHere is the full Aug-IQN pipeline in code, combining all three steps:\n\n::: {.cell execution_count=7}\n``` {.python .cell-code code-fold=\"false\"}\ndef augiqn_pipeline(X_train, y_train, X_test,\n                    clf_hdim=256, clf_layers=3, clf_epochs=3000,\n                    iqn_epochs=8000, iqn_hdim=256, seed=0):\n    \"\"\"Aug-IQN: EM clustering + classifier + augmented IQN.\n\n    Args:\n        X_train: (n_train, d) training inputs\n        y_train: (n_train,) training responses\n        X_test:  (n_test, d) test inputs\n        clf_hdim:   classifier hidden dimension\n        clf_layers: classifier hidden layers\n        clf_epochs: classifier training epochs\n        iqn_epochs: IQN training epochs\n        iqn_hdim:   IQN hidden dimension\n        seed:       random seed\n\n    Returns:\n        quantile_samples: (B, n_test) array of quantile predictions\n    \"\"\"\n    # Step 1: EM clustering on Y\n    labels = cluster_responses(y_train, seed=seed)\n\n    # Step 2: Train boundary classifier\n    clf, x_mean, x_std, acc = train_classifier(\n        X_train, labels,\n        hdim=clf_hdim, n_layers=clf_layers,\n        epochs=clf_epochs, seed=seed\n    )\n\n    # Get regime probabilities\n    Xt_tr = torch.tensor((X_train - x_mean) / x_std, dtype=torch.float32)\n    Xt_te = torch.tensor((X_test - x_mean) / x_std, dtype=torch.float32)\n    with torch.no_grad():\n        fhat_train = clf.predict_prob(Xt_tr).numpy()\n        fhat_test = clf.predict_prob(Xt_te).numpy()\n\n    # Step 3: Augment inputs and train IQN\n    X_aug_train = np.column_stack([X_train, fhat_train])\n    X_aug_test = np.column_stack([X_test, fhat_test])\n\n    # Train IQN on augmented inputs (using pinball-dominant loss)\n    from gbc.iqn import train_iqn, sample_iqn\n    model, xm, xs, ym, ys = train_iqn(\n        X_aug_train, y_train,\n        epochs=iqn_epochs, hdim=iqn_hdim,\n        w=(0.10, 0.20, 0.70), seed=seed\n    )\n\n    quantile_samples = sample_iqn(\n        model, X_aug_test, xm, xs, ym, ys, B=500\n    )\n    return quantile_samples, acc\n```\n:::\n\n\n::: {.callout-tip}\n*Practical note.* The `train_iqn` and `predict_quantiles` functions are the same ones from @sec-iqn-training, the IQN does not know or care that its input has been augmented. The only change is that `xdim` increases by one. This modularity is a design feature: the augmentation step is a preprocessing wrapper, not an architectural modification.\n:::\n\nAn alternative to feature augmentation is an *implicit* approach: a mixture-of-experts (MoE) IQN where a learned gating network routes each input to one of $K$ expert heads. The gating network would implicitly learn the boundary, and each expert would specialize in one regime.\n\nWe tested this approach and it failed. The core issue is that the softmax gate used in standard MoE architectures is inherently smooth, it cannot represent a step function in input space. With soft routing (weighted average of experts), the gate never commits to a single expert per region. We measured the mean specialization (the maximum gate weight for each input) and found it was only 0.64--0.71 out of 1.0, meaning each input activates both experts nearly equally. The resulting predictions are no better than a single IQN (CRPS 0.036--0.039 vs. 0.031). With hard routing (argmax at inference), individual experts produce catastrophic predictions (CRPS $> 0.59$) because they were trained to contribute partial signals under soft mixing and cannot produce valid standalone predictions.\n\nFor sharp discontinuities, *explicit* boundary detection (EM + classifier) followed by feature augmentation is far superior to *implicit* boundary learning via gating networks. The boundary is a hard combinatorial structure that smooth gating functions cannot capture. This negative result is worth documenting because MoE architectures have been extraordinarily successful in other domains, large language models, image generation, speech recognition, where the \"experts\" specialize in different semantic categories. The difference is that in those domains, the gating function needs to distinguish between gradually varying categories (nouns vs. verbs, indoor vs. outdoor scenes), not between regions separated by a geometric boundary with zero-width transition. Jump processes are a special case where implicit gating fails and explicit detection is required.\n\n\n### Why Ensembling Hurts on Jump Data {#sec-jumps-ensembling}\n\nEnsembling *hurts* on jump data. On smooth datasets like the motorcycle crash data, ensembling $K$ IQN members improves CRPS by reducing variance. On jump data, ensembling has the opposite effect.\n\nThe mechanism is *boundary-location blur*. Each ensemble member localizes the discontinuity at a slightly different position in input space, because the training data provides only noisy evidence about the exact boundary location. When we pool quantile samples across members, the pooled distribution near the boundary is a mixture of member-specific predictions that are each sharp but disagree about the boundary location. The result is a blurred transition that is worse than any individual member's prediction.\n\nTo see this concretely, consider a simple 1D example with a jump at $x = 0.5$. Suppose we train three IQN ensemble members on the same data but with different random seeds. Member A places the jump at $x = 0.48$, member B at $x = 0.51$, and member C at $x = 0.52$. At the true boundary $x = 0.50$, member A predicts regime 1 (correct for that member's learned boundary), member B predicts regime 0, and member C predicts regime 0. The ensemble average at $x = 0.50$ is therefore a weighted average of two regime-0 predictions and one regime-1 prediction, a blurred, intermediate value that does not correspond to either regime.\n\nThe blurring extends over the entire strip $[0.48, 0.52]$ where the members disagree about the boundary location. Within this strip, the ensemble's pooled quantile function transitions smoothly from regime 0 to regime 1, exactly mimicking the GP pathology that we are trying to avoid. Outside this strip, all members agree and the ensemble behaves normally.\n\nThe width of the blur strip depends on the variability of boundary localization across members. On smooth data, there is no boundary to localize, so this mechanism does not arise and ensembling provides its usual variance-reduction benefit. On jump data, the boundary is the critical feature, and any disagreement about its location produces blurring at exactly the place where sharpness matters most.\n\n@fig-ensemble-blur-illustration provides a schematic illustration of this mechanism.\n\nWe can make this more precise. Let $b_k$ denote the boundary location learned by ensemble member $k$, and suppose the true boundary is at $b^*$. Each member's quantile prediction at a test point $x$ takes the form\n$$\nQ_k(\\tau \\mid x) \\approx \\begin{cases} Q_0(\\tau \\mid x) & \\text{if } x < b_k, \\\\ Q_1(\\tau \\mid x) & \\text{if } x \\geq b_k, \\end{cases}\n$$\nwhere $Q_0$ and $Q_1$ are the within-regime quantile functions. The ensemble's pooled prediction is $\\bar{Q}(\\tau \\mid x) = K^{-1} \\sum_k Q_k(\\tau \\mid x)$, which at a point $x$ in the strip $[\\min_k b_k, \\max_k b_k]$ is a convex combination of $Q_0$ and $Q_1$ with weights determined by the fraction of members that place $x$ below their respective $b_k$. The blur strip has width of order $W = \\max_k b_k - \\min_k b_k \\approx 4\\hat{\\sigma}_b$ (two standard deviations on each side of $b^*$), where $\\hat{\\sigma}_b = \\mathrm{std}_k(b_k)$. Within this strip, $\\bar{Q}(\\tau \\mid x)$ is a mixture of $Q_0$ and $Q_1$ with mixing weight $\\alpha(x) = K^{-1} \\sum_k \\mathbf{1}[x < b_k]$, which transitions smoothly from 1 to 0 as $x$ moves from $\\min_k b_k$ to $\\max_k b_k$. The CRPS penalty from the mixture exceeds the optimal $\\mathrm{CRPS}(Q_j, y)$ by an amount proportional to $\\alpha(x) \\cdot W_1(Q_0, Q_1) \\lesssim \\alpha(x) \\cdot \\Delta$ [@gneiting2007strictly], where $W_1$ is the Wasserstein-1 distance and $\\Delta = \\mathbb{E}|Q_1(U) - Q_0(U)|$ is the mean jump size. This analysis confirms that the blur penalty grows with the jump size and the boundary-localization variance. This is exactly the smooth transition that the GP produces, and that Aug-IQN avoids by providing a single, shared boundary estimate to the IQN.\n\n::: {.cell fig-height='3.5' fig-width='7' execution_count=8}\n``` {.python .cell-code}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nnp.random.seed(17)\n\nx = np.linspace(0, 1, 500)\n# True jump function: step from 0 to 13 at x=0.50\ntrue_boundary = 0.50\ny_true = np.where(x >= true_boundary, 13.0, 0.0)\n\n# Ensemble members: each learns a slightly different boundary\nK = 5\nboundaries = np.array([0.47, 0.49, 0.51, 0.52, 0.53])\ncolors_members = ['#aaaaaa'] * K\n\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(9, 3.5), sharey=True)\n\n# Left panel: individual members\nfor i, b in enumerate(boundaries):\n    y_k = np.where(x >= b, 13.0, 0.0)\n    ax1.plot(x, y_k, color='#aaaaaa', lw=1.5, alpha=0.7,\n             label='Ensemble members' if i == 0 else '_nolegend_')\nax1.plot(x, y_true, 'b-', lw=2, label='True boundary (x=0.50)')\nax1.axvspan(boundaries.min(), boundaries.max(), alpha=0.12, color='red',\n            label=f'Disagreement strip [{boundaries.min():.2f}, {boundaries.max():.2f}]')\nax1.axvline(true_boundary, color='blue', lw=1, ls='--', alpha=0.5)\nax1.set_xlabel('x')\nax1.set_ylabel('Predicted median')\nax1.set_title('Individual ensemble members')\nax1.legend(fontsize=8, loc='upper left')\nax1.set_ylim(-1.5, 15)\n\n# Right panel: ensemble average vs. single model\ny_ensemble = np.mean([np.where(x >= b, 13.0, 0.0) for b in boundaries], axis=0)\nax2.plot(x, y_ensemble, 'r--', lw=2.5, label='Ensemble average (blurred)')\nax2.plot(x, y_true, 'b-', lw=2, label='Single model (sharp)')\nax2.axvspan(boundaries.min(), boundaries.max(), alpha=0.12, color='red')\nax2.axvline(true_boundary, color='blue', lw=1, ls='--', alpha=0.5)\nax2.set_xlabel('x')\nax2.set_title('Ensemble average vs. single model')\nax2.legend(fontsize=8, loc='upper left')\nax2.set_ylim(-1.5, 15)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Ensemble blurring on a synthetic 1D jump function. Each ensemble member (thin gray lines) learns a sharp boundary at a slightly different location. The ensemble average (red dashed) produces a smooth transition across the disagreement strip [0.48, 0.52], exactly mimicking the GP pathology. A single model with a sharp boundary (true boundary at 0.50, blue) avoids this blur.](ch08-jumps_files/figure-pdf/fig-ensemble-blur-illustration-output-1.pdf){#fig-ensemble-blur-illustration fig-pos='H'}\n:::\n:::\n\n\nThe practical recommendation for jump data is simple: use a single model with the pinball-dominant loss, not an ensemble.\n\n\n## Phantom Function {#sec-jumps-phantom}\n\nThe Phantom dataset from @flowers2026modular is a standard benchmark for jump-process surrogates.\n\nThe Phantom function is a bivariate response ($d = 2$, $N = 10{,}201$) with a *sinusoidal jump boundary*: the response jumps across the curve defined by $x_2 = \\sin(x_1)$ in the unit square $[{-0.5}, {0.5}]^2$. Points above the sine curve belong to one regime and points below belong to another. Each regime generates the response from a different Gaussian process realization, specifically, $f_1 \\sim \\mathcal{GP}(\\mu_1, k_1)$ and $f_2 \\sim \\mathcal{GP}(\\mu_2, k_2)$ with well-separated means $\\mu_1 \\neq \\mu_2$, producing a bimodal marginal distribution with a sharp level shift across the boundary.\n\nThe sinusoidal boundary is challenging for several reasons. First, axis-aligned partitions fail because tree-based methods like treed GPs cannot approximate a sine curve with axis-aligned splits; the number of rectangular cells needed to approximate $x_2 = \\sin(x_1)$ grows rapidly with resolution, and each cell contains a mixture of both regimes near the curve. Second, the sine curve oscillates, so the boundary crosses the domain multiple times in the $x_1$ direction. A neighborhood of radius $r$ around any point near the boundary will contain points from both regimes, and the proportion of \"wrong-regime\" neighbors depends on the local orientation and curvature of the sine wave. Third, linear classifiers fail outright: an SVC with a linear kernel achieves only 82% accuracy on this boundary, because no hyperplane can separate the two nested curvilinear regions. Radial basis function kernels do better (around 96%), but still fall short of the MLP's 99.98%.\n\nMore broadly, the Phantom boundary is representative of a wide class of real-world jump boundaries that are smooth but nonlinear. In materials science, phase boundaries are often curved surfaces in composition-temperature space. In fluid dynamics, shock waves form curved manifolds in the Mach-angle-of-attack space. The sinusoidal geometry captures the essential challenge of these boundaries: they are smooth enough that a sufficiently flexible classifier can learn them, but nonlinear enough that simple classifiers fail.\n\nThis geometry makes the Phantom an ideal test case for Aug-IQN. The EM clustering step is easy because the two regimes have well-separated means, so the marginal histogram is clearly bimodal. The classification step is the bottleneck: the classifier must learn a nonlinear decision boundary that tracks the sine wave through the input domain. The MLP's universal approximation capacity is essential here, a linear or even polynomial classifier would introduce systematic errors over large regions of the input space, corrupting the downstream IQN.\n\nWe compare three methods using the @flowers2026modular protocol: 90/10 train/test split, 20 replicates, full training set ($n_{\\mathrm{train}} \\approx 9{,}000$). Response values are normalized to $[0, 1]$.\n\n| Method | RMSE | CRPS | 90% Coverage | Time/rep |\n|:----|:----:|:----:|:------:|:-----:|\n| MJGP [@flowers2026modular] | 0.053 $\\pm$ 0.001 | 0.010 $\\pm$ 0.000 |, | ~600s |\n| Plain GBC | 0.095 $\\pm$ 0.001 | 0.031 $\\pm$ 0.001 | 0.89 | 18s |\n| **Aug-IQN** | *0.044 $\\pm$ 0.002* | *0.009 $\\pm$ 0.000* | *0.91* | *23s* |\n\n: Phantom benchmark ($d = 2$, $n = 9$k): Aug-IQN vs. MJGP and plain GBC. Mean $\\pm$ SE over 20 replicates. Aug-IQN marginally outperforms MJGP on CRPS and is $26\\times$ faster. {#tbl-phantom}\n\nWithout boundary information, plain GBC struggles with the sinusoidal jump, a $3\\times$ CRPS gap versus MJGP (@tbl-phantom). Adding the classifier closes that gap entirely: Aug-IQN marginally outperforms MJGP on CRPS, improves RMSE by 17%, and runs $26\\times$ faster, reflecting both the $\\mathcal{O}(n)$ vs. $\\mathcal{O}(n^3)$ algorithmic difference and GPU acceleration. Coverage is well-calibrated at 91%.\n\nThe role of loss-weight selection is also important. A loss-weight ablation on Phantom (20 replicates, 6,000 epochs) confirms that the pinball-dominant configuration is optimal for jump data: $(0.05, 0.25, 0.70)$ gives CRPS = 0.033; $(0.00, 0.30, 0.70)$ gives 0.035; and the selected $(0.10, 0.20, 0.70)$ gives 0.031. Removing the $L_1$ anchor entirely ($w_1 = 0$) degrades performance, suggesting that a small anchor term stabilizes optimization without biasing the quantile estimates toward the boundary average. The largest gain, 20% on Phantom, comes from this loss reweighting alone, before any augmentation is applied. The gain decreases as the boundary becomes less sharp: 15% on Star, 9% on Michalewicz, and only 5% on the smooth AMHV.\n\nThe RMSE improvement (0.044 vs. 0.053) is worth discussing separately. MJGP fits a separate GP on each side of the boundary. Within each regime, the local GP must estimate its own length-scale and noise-variance parameters from only the subset of training points assigned to that regime. Near the boundary, the effective sample size for each local GP shrinks, because the assignment step removes points on the other side of the boundary. The IQN, by contrast, trains on *all* the data simultaneously with the augmented feature differentiating regimes. This pooling of information across the entire dataset gives the IQN a statistical advantage, especially in regions where one regime has relatively few training points.\n\n\n## Star Function {#sec-jumps-star}\n\nThe Star dataset ($d = 2$, $N = 10{,}201$) from @flowers2026modular replaces the smooth sinusoidal boundary with an angular, star-shaped partition. The boundary is a five-pointed star centered in the unit square, with the interior of the star forming one regime and the exterior forming another. Every point in the interior regime is geographically close to the exterior regime, the star's tips extend nearly to the domain boundary, and the indentations between tips bring the exterior regime close to the center.\n\nThe star-shaped boundary creates compounding difficulties beyond the Phantom benchmark. At each of the five tips, the boundary has sharp corners where the two regimes nearly touch with zero separation. Unlike the Phantom's smooth sine curve, which has bounded curvature everywhere, the star's angular geometry has formally infinite curvature at the tips. This means that any classifier with a smooth decision boundary, including the MLP with sigmoid output, must approximate a corner with a rapid but continuous turn, inevitably misclassifying a thin wedge of points near each tip. With five tips and five indentations, there are ten such problematic locations, compared to the Phantom's gently oscillating sine wave that has no sharp corners at all.\n\nNeighborhood mixing is also severe on the Star dataset. At the star's tips, points from both regimes are densely interleaved within any small ball. The boundary length relative to the domain area is larger for the star than for the sine curve, meaning that a greater fraction of the total training points lie near the boundary where classification is uncertain. Put differently, the Star benchmark stress-tests the classifier more aggressively than the Phantom, requiring the MLP to learn fine-grained local structure at ten distinct boundary segments simultaneously.\n\nThe MLP classifier still achieves over 99% accuracy on Star, because the EM clustering step produces clean labels and the MLP has sufficient capacity to represent the angular boundary. The three-layer architecture is essential: shallower networks (one hidden layer) struggle with the sharp corners because they approximate the boundary with a piecewise-linear surface that has too few segments to track ten angular features.\n\nThe contrast between Phantom and Star illuminates when depth matters for the classifier. The Phantom's smooth sine boundary can be approximated reasonably well by a shallow network with many units, a wide, shallow network can learn a smooth decision surface. The Star's angular boundary, with its ten sharp corners, requires *compositional* features: the network must compose local angular detectors to form the global star shape. This compositional structure is exactly what depth provides. A two-layer network composes simple features (edges, half-planes) into more complex ones (angles, wedges), and a three-layer network composes these into the full star geometry. This depth advantage is a specific instance of the general principle that deep networks can represent compositional functions exponentially more efficiently than shallow ones.\n\n| Method | RMSE | CRPS | 90% Coverage | Time/rep |\n|:----|:----:|:----:|:------:|:-----:|\n| MJGP [@flowers2026modular] | 0.085 $\\pm$ 0.001 | 0.024 $\\pm$ 0.001 |, | ~600s |\n| Plain GBC | 0.124 $\\pm$ 0.001 | 0.045 $\\pm$ 0.001 | 0.87 | 18s |\n| **Aug-IQN** | *0.059 $\\pm$ 0.002* | *0.013 $\\pm$ 0.000* | *0.89* | *22s* |\n\n: Star benchmark ($d = 2$, $n = 9$k): Aug-IQN outperforms MJGP by 46% on CRPS. {#tbl-star}\n\nOn the Star dataset (@tbl-star), Aug-IQN's advantage over MJGP is *larger* than on Phantom: CRPS improves by 46%, RMSE by 31%, and the $27\\times$ speedup holds.\n\nWhy does Aug-IQN's advantage grow on the harder dataset? MJGP fits a separate GP on each side of the boundary, and the angular star geometry creates thin regions where each local GP has relatively few training points. The GP's cubic scaling limits the amount of local data it can use. The IQN, by contrast, trains on *all* the data simultaneously and uses the augmented feature to differentiate regimes. It can use patterns learned in data-rich regions to improve predictions in data-poor regions near the star's tips. The star geometry also exacerbates the GP's length-scale problem: near the tips, the two regimes are so close together that the local GP's length scale must be very short, which reduces the effective sample size for each local GP even further. In quantitative terms, a star tip with an opening angle of $36°$ (for a regular five-pointed star) creates a wedge-shaped region where the nearest boundary segment is only a few percent of the domain width away. A local GP assigned to this wedge has very few training points, perhaps only 2--3% of the total training set, making hyperparameter estimation unreliable and inflating posterior uncertainty.\n\nAcross both datasets, the three-step Aug-IQN pipeline produces better CRPS and better RMSE than MJGP, runs $27\\times$ faster, and achieves well-calibrated 90% coverage (0.91 on Phantom, 0.89 on Star). The key enabling factor is classifier accuracy. When the MLP achieves $>99\\%$ accuracy on the boundary, the augmented IQN receives nearly perfect regime information, and the downstream quantile estimation becomes a smooth-function regression problem where neural networks excel.\n\nOn both Phantom and Star, Aug-IQN's empirical 90% coverage (0.91 and 0.89, respectively) is close to the nominal level, with a single model and no post-hoc calibration. The slight under-coverage on Star (0.89 vs. the nominal 0.90) is consistent with the harder boundary geometry: the thin misclassified wedges near the star tips produce a small number of test points where the prediction intervals are too narrow because the IQN assigns them to the wrong regime. This is a local effect confined to the boundary neighborhood and does not affect the bulk of the test points, which is why the overall coverage remains close to nominal. For applications requiring guaranteed coverage, the conformal calibration methods of @sec-calibration can be applied as a post-processing step.\n\n\n## AMHV Function {#sec-jumps-amhv}\n\nNot every dataset with regime structure benefits from augmentation. The AMHV (Automated Material Handling Vehicle) transport dataset [@kang2024bayesian] illustrates when plain GBC is better.\n\nAMHV records average transport time (seconds) for autonomous vehicles in a semiconductor wafer fabrication facility ($N = 9{,}503$, $d = 4$). The facility uses fleets of small robotic vehicles that carry wafer cassettes between processing stations on an overhead rail network. Each vehicle receives a pickup order, navigates to the source station, collects a cassette, and delivers it to the destination station along a shortest-path route. The four input parameters control different aspects of this logistics system: vehicle speed (how fast each vehicle moves along the rail), acceleration (how quickly it reaches cruising speed), minimum inter-vehicle distance (the safety gap maintained between consecutive vehicles on the same rail segment), and empty-vehicle search range (how far the dispatch system looks for an idle vehicle when a new pickup order arrives). At low utilization, changing any of these parameters produces a smooth, predictable effect on average transport time, faster vehicles mean shorter trips, and the relationship is nearly linear. But as the system approaches capacity saturation, the vehicles begin to interfere with each other. A vehicle waiting behind a slower vehicle on a single-lane rail segment cannot pass, creating cascading delays that propagate through the network. At some combination of high speed, tight safety gaps, and wide search ranges, the system tips into a congested regime where average transport time jumps sharply upward.\n\nSemiconductor fabrication facilities (fabs) are among the most expensive manufacturing environments in the world, with individual facilities costing $10$--$20$ billion to construct. The AMHV system is responsible for moving work-in-progress between hundreds of processing tools, and the throughput of the entire fab depends on the AMHV's efficiency. Even a 1% improvement in average transport time can translate to millions of dollars in annual revenue. This makes the AMHV an ideal candidate for surrogate-based optimization: the simulator is expensive to run (each evaluation requires simulating the full fab for a realistic production schedule), and the response surface is non-trivial because of the congestion effects.\n\nThis capacity-induced phase transition produces a response surface that looks like a jump discontinuity in four-dimensional input space. But unlike the clean binary jumps in Phantom and Star, the AMHV transition is *gradual*. There is no sharp sine curve or star-shaped boundary separating two regions; instead, there is a fuzzy transition zone where congestion builds gradually as the system approaches its capacity limit. The marginal distribution of response values is not cleanly bimodal, the two regimes overlap substantially in the marginal, with many intermediate transport times that could belong to either the smooth or congested regime.\n\nThis overlap means EM clustering cannot reliably separate the two regimes. Applying the augmentation pipeline to AMHV would produce noisy regime labels, a poorly trained classifier, and ultimately an augmented feature that provides more confusion than information.\n\n| Method | RMSE | CRPS | 90% Coverage |\n|:----|:----:|:----:|:------:|\n| MJGP [@flowers2026modular] | 0.027 $\\pm$ 0.000 | 0.012 $\\pm$ 0.000 |, |\n| *Plain GBC* | *0.024 $\\pm$ 0.000* | *0.011 $\\pm$ 0.000* | *0.91* |\n\n: AMHV benchmark ($d = 4$, $n = 8.5$k): Plain GBC outperforms MJGP without augmentation. The jump-detection step in MJGP introduces overhead when the boundary is smooth. {#tbl-amhv}\n\nOn AMHV (@tbl-amhv), plain GBC outperforms MJGP on both RMSE and CRPS without any augmentation. The difference is small but telling: MJGP's jump-detection machinery introduces overhead that does not pay off when the boundary is smooth rather than sharp.\n\nThis illustrates a recurring pattern: *specialized methods can hurt when their structural assumptions are not well-matched to the data*. The IQN's architecture is flexible enough to handle the smooth AMHV boundary without explicit jump detection. Its feedforward layers learn a locally varying quantile function that captures the gradual transition between regimes.\n\nThe guideline: augment when the response histogram is clearly bimodal, as for Phantom and Star. Do not augment when the response modes overlap, the boundary is smooth, or the data has more than two regimes; in those cases, plain GBC already handles the non-stationarity, as AMHV illustrates. Plotting the marginal response distribution costs only seconds and can save hours of unnecessary experimentation.\n\nA useful quantitative diagnostic is the *overlap coefficient* of the fitted two-component Gaussian mixture. After fitting the GMM, compute the probability that a random draw from component 1 falls in the higher-density region of component 2. If this overlap exceeds 10--15%, the modes are not well-separated and augmentation is unlikely to help. For Phantom and Star, the overlap coefficient is effectively zero (the modes are separated by many standard deviations). For AMHV, it is approximately 25%, confirming that EM clustering cannot reliably separate the regimes. We formalize this diagnostic in @exr-amhv-diagnostic.\n\n\n## Summary of Jump-Process Benchmarks {#sec-jumps-summary}\n\n@tbl-summary collects results across all datasets discussed in this chapter, together with the Michalewicz benchmark ($d = 4$, $N = 90{,}000$) where MJGP is computationally infeasible ($\\geq 48$ hours) but GBC trains in under 30 minutes.\n\n| Dataset | $d$ | $n$ | Best Method | CRPS | vs. MJGP |\n|:-----|:---:|:---:|:------|:----:|:-----:|\n| Phantom | 2 | 9k | Aug-IQN | 0.009 | +10% better |\n| Star | 2 | 9k | Aug-IQN | 0.013 | +46% better |\n| AMHV | 4 | 8.5k | Plain GBC | 0.011 | +8% better |\n| Michalewicz | 4 | 90k | Plain GBC | 0.031 | MJGP infeasible |\n\n: Summary of GBC performance across jump-process benchmarks. GBC (plain or augmented) wins on every dataset. {#tbl-summary}\n\nGBC wins on every dataset (@tbl-summary). Aug-IQN beats MJGP on the sharp-jump datasets while running $27\\times$ faster; plain GBC wins on AMHV without augmentation; and on Michalewicz ($n = 90{,}000$), MJGP is infeasible while GBC trains in under 30 minutes.\n\nThe Michalewicz benchmark deserves a brief comment. The standard Michalewicz function in $d = 4$ dimensions is modified by adding a 0.5 offset wherever $f(x) \\geq -0.01$ (the precise definition is in @sec-data-michalewicz), introducing a jump discontinuity along the level set $\\{x : f(x) = -0.01\\}$. Unlike Phantom and Star, the marginal response is not bimodal, it is a point mass near 0.5 plus a scattered distribution in $[-4, 0]$, violating the Gaussian-mixture clustering assumption. Augmentation would fail here because EM cannot identify two clean modes. But with $n_{\\mathrm{train}} = 90{,}000$ training points, the plain IQN has enough data to learn the jump structure directly from the input-output relationship, achieving CRPS = 0.031 without any boundary-detection preprocessing. This confirms our earlier point: augmentation is a tool for when it is needed, not a blanket prescription.\n\nThe pattern: when the response histogram is clearly bimodal and the modes are well-separated, apply Aug-IQN. When the response modes overlap, or when the response has more than two distinct levels without clear separation, use plain GBC. A quick histogram plot is all that is needed to make this decision.\n\n\n## Three Regimes and Beyond {#sec-jumps-three-regimes}\n\nThe Aug-IQN pipeline as described above assumes a binary jump structure: two regimes, two Gaussian mixture components, one binary classifier. The approach generalizes to three or more regimes with straightforward modifications to each step of the pipeline.\n\nConsider a 1D response surface with three regimes separated by jump boundaries at $x = -0.3$ and $x = 0.4$:\n$$\nf(x) = \\begin{cases} \\sin(2\\pi x) & \\text{if } x < -0.3, \\\\ 3 + 0.5\\cos(\\pi x) & \\text{if } -0.3 \\leq x < 0.4, \\\\ 6 + 0.3x & \\text{if } x \\geq 0.4, \\end{cases}\n$$ {#eq-three-regime}\nwith additive noise $\\varepsilon \\sim \\mathcal{N}(0, 0.2^2)$ and $x \\in [-1, 1]$. The marginal response distribution has three modes, corresponding to the three distinct response levels.\n\nThe modifications to the pipeline are minimal. In the EM step, we fit a three-component Gaussian mixture instead of a two-component one. The `cluster_responses` function already accepts an `n_components` argument, so this requires no code change. The hard labels are now $c_i \\in \\{0, 1, 2\\}$, and the assignment convention orders them by increasing component mean.\n\nThe classification step changes from binary to multiclass. We replace the sigmoid output with a softmax over three classes, and the binary cross-entropy loss becomes categorical cross-entropy. The classifier now outputs a probability vector $[\\hat{p}_0(x), \\hat{p}_1(x), \\hat{p}_2(x)]$ for each input $x$, where $\\hat{p}_k(x) = P(c = k \\mid x)$ and $\\sum_k \\hat{p}_k(x) = 1$.\n\nThe augmented input becomes $\\tilde{x} = [x, \\hat{p}_0(x), \\hat{p}_1(x)] \\in \\mathbb{R}^{d+2}$. We include only two of the three probabilities because the third is redundant: $\\hat{p}_2(x) = 1 - \\hat{p}_0(x) - \\hat{p}_1(x)$. In general, a $K$-regime problem augments the input with $K-1$ probability features.\n\n::: {.cell execution_count=9}\n``` {.python .cell-code code-fold=\"true\"}\nnp.random.seed(123)\nn3 = 600\nx3 = np.random.uniform(-1, 1, n3)\n\n# Three-regime response\ny3 = np.where(x3 < -0.3,\n              np.sin(2 * np.pi * x3) + 0.2 * np.random.randn(n3),\n              np.where(x3 < 0.4,\n                       3.0 + 0.5 * np.cos(np.pi * x3) + 0.2 * np.random.randn(n3),\n                       6.0 + 0.3 * x3 + 0.2 * np.random.randn(n3)))\n\n# EM clustering with 3 components\nlabels3 = cluster_responses(y3, n_components=3)\n# Sort labels by mean response\nmeans = [y3[labels3 == k].mean() for k in range(3)]\norder = np.argsort(means)\nrelabel = np.zeros_like(labels3)\nfor new, old in enumerate(order):\n    relabel[labels3 == old] = new\nlabels3 = relabel\n\n# Train 3-class classifier\nclass MultiClassifier(nn.Module):\n    def __init__(self, xdim, n_classes=3, hdim=128, n_layers=2):\n        super().__init__()\n        layers = [nn.Linear(xdim, hdim), nn.ReLU()]\n        for _ in range(n_layers - 1):\n            layers += [nn.Linear(hdim, hdim), nn.ReLU()]\n        layers += [nn.Linear(hdim, n_classes)]\n        self.net = nn.Sequential(*layers)\n    def forward(self, x):\n        return self.net(x)\n\ntorch.manual_seed(42)\nX3 = x3.reshape(-1, 1)\nx3_mean, x3_std = X3.mean(0), X3.std(0) + 1e-8\nXt3 = torch.tensor((X3 - x3_mean) / x3_std, dtype=torch.float32)\nyt3 = torch.tensor(labels3, dtype=torch.long)\n\nmclf = MultiClassifier(1, n_classes=3, hdim=128, n_layers=2)\nopt3 = torch.optim.Adam(mclf.parameters(), lr=1e-3, weight_decay=1e-4)\nsched3 = torch.optim.lr_scheduler.CosineAnnealingLR(opt3, T_max=2000, eta_min=1e-5)\nmclf.train()\nfor _ in range(2000):\n    opt3.zero_grad()\n    loss3 = nn.functional.cross_entropy(mclf(Xt3), yt3)\n    loss3.backward()\n    opt3.step()\n    sched3.step()\nmclf.eval()\n\nxg3 = np.linspace(-1, 1, 500).reshape(-1, 1)\nXtg3 = torch.tensor((xg3 - x3_mean) / x3_std, dtype=torch.float32)\nwith torch.no_grad():\n    probs3 = torch.softmax(mclf(Xtg3), dim=1).numpy()\n\ncolors3 = ['steelblue', 'coral', 'forestgreen']\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 3.5))\n\nfor k in range(3):\n    mask = labels3 == k\n    ax1.scatter(x3[mask], y3[mask], s=8, alpha=0.5, color=colors3[k], label=f'Regime {k}')\nax1.axvline(-0.3, color='k', ls='--', lw=1, alpha=0.5)\nax1.axvline(0.4, color='k', ls='--', lw=1, alpha=0.5)\nax1.set_xlabel(\"x\"); ax1.set_ylabel(\"y\")\nax1.set_title(\"Three-regime data (EM labels)\")\nax1.legend(fontsize=8)\n\nfor k in range(3):\n    ax2.plot(xg3, probs3[:, k], color=colors3[k], lw=2, label=f'P(regime={k}|x)')\nax2.axvline(-0.3, color='k', ls='--', lw=1, alpha=0.5)\nax2.axvline(0.4, color='k', ls='--', lw=1, alpha=0.5)\nax2.set_xlabel(\"x\"); ax2.set_ylabel(\"Probability\")\nax2.set_title(\"Three-class classifier\")\nax2.legend(fontsize=8)\nax2.set_ylim(-0.05, 1.05)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n/var/folders/x2/q3y_n1tn59l2_s1cyn31v28r0000gn/T/ipykernel_12328/3094557271.py:15: RuntimeWarning:\n\nMean of empty slice\n\n/Users/vsokolov/miniconda3/lib/python3.13/site-packages/numpy/_core/_methods.py:142: RuntimeWarning:\n\ninvalid value encountered in scalar divide\n\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Three-regime jump surface with EM clustering and multiclass classification. Left: the raw data with three regimes colored by EM-inferred labels. Right: the three-class classifier probabilities, showing sharp transitions at both boundaries.](ch08-jumps_files/figure-pdf/fig-three-regimes-output-2.pdf){#fig-three-regimes fig-pos='H'}\n:::\n:::\n\n\n@fig-three-regimes shows the three-regime generalization in action. The EM clustering step cleanly separates the three modes in the marginal response distribution, and the multiclass classifier learns sharp transitions at both boundaries $x = -0.3$ and $x = 0.4$. The augmented input provides the IQN with two probability features that encode the regime structure, allowing it to learn three separate quantile functions that match the smooth within-regime behavior.\n\nThe three-regime case illustrates a general principle: the Aug-IQN pipeline decomposes the jump-process emulation problem into a classification subproblem and a set of smooth regression subproblems. The number of regimes $K$ affects the classification step (which must now learn $K-1$ decision boundaries) and the dimension of the augmented input ($d + K - 1$ instead of $d + 1$), but the IQN architecture is unchanged. In practice, the main limitation is the EM clustering step, which requires that the $K$ regimes produce $K$ well-separated modes in the marginal response distribution. If two regimes have similar response levels but different spatial locations, the marginal modes will overlap and EM will fail to separate them. For such cases, spatially-aware clustering methods (e.g., fitting the mixture model jointly on $[x, y]$ rather than $y$ alone) may be needed.\n\nHow do we choose $K$? In practice, the number of regimes is often known from domain knowledge, the physicist knows there are two phases, the engineer knows there is a single congestion threshold. When $K$ is unknown, standard model selection criteria (BIC, AIC, or the silhouette score) can be applied to the Gaussian mixture fit. Over-estimating $K$ is less harmful than under-estimating it: if we fit three components to a two-regime dataset, one component will capture a portion of one regime and the classifier will learn a boundary that does not exist, adding a harmless but unnecessary extra feature to the IQN input. Under-estimating $K$ is more dangerous, because a two-component fit applied to a three-regime response will merge two regimes, producing misclassified labels that corrupt the downstream IQN.\n\nAs a practical safeguard, we recommend fitting GMMs for $K = 2, 3, 4, 5$ and selecting the $K$ that minimizes BIC. On the three-regime synthetic data in @eq-three-regime, BIC correctly identifies $K = 3$ in all of our test runs. On the two-regime Phantom data, BIC correctly selects $K = 2$. The entire model-selection sweep takes under a second, because the GMM is fit to the one-dimensional response vector only.\n\n\n## Comparison to Other Jump Methods {#sec-jumps-comparison}\n\nSeveral methods in the computer experiments literature are designed specifically for response surfaces with discontinuities.\n\n*Treed GPs* [@gramacy2008bayesian] partition the input space into axis-aligned rectangular regions and fit an independent GP within each region. The partition is learned by a Bayesian tree model (CART-like), with the tree depth and split locations determined by a reversible-jump MCMC algorithm. Treed GPs were among the first methods to address jump discontinuities in the surrogate modeling literature, and they remain a popular default in the `tgp` R package. Their strength is that they make no assumption about boundary geometry, the tree can place a split anywhere along any coordinate axis. Their weakness is that axis-aligned splits are a poor representation of curved or diagonal boundaries. Approximating the sinusoidal Phantom boundary requires a fine grid of axis-aligned rectangles, each of which contains data from both regimes near the boundary. The tree depth needed to resolve the boundary scales with the boundary's curvature, and deep trees suffer from the usual bias-variance tradeoff: each leaf region has fewer data points, so the local GP has higher variance.\n\n*Voronoi tessellation methods* generalize axis-aligned partitions to arbitrary polyhedral cells. Instead of splitting along coordinate axes, a Voronoi partition is defined by a set of seed points, and each cell contains all inputs closer to a given seed than to any other. The boundary between cells is a hyperplane, and the union of cell boundaries forms a piecewise-linear approximation to the true jump boundary. This is more flexible than axis-aligned trees but still geometry-dependent: a curved boundary like the Phantom's sine wave requires many Voronoi cells to approximate, and the number of seed points (and hence the number of local GPs) must grow with the boundary's complexity. Additionally, Voronoi methods face a chicken-and-egg problem: the optimal seed locations depend on the boundary geometry, which is exactly what we are trying to learn. Most implementations use a two-stage approach, an initial rough partition followed by iterative refinement, but convergence is not guaranteed and the final partition quality depends strongly on initialization.\n\n*Modular Jump GPs (MJGP)* [@flowers2026modular] are the closest competitor to Aug-IQN and share the same EM + classifier preprocessing pipeline. The key difference is in the downstream model. MJGP uses the EM labels to partition the data into two subsets, fits a separate GP on each subset using the augmented input $[x, \\hat{f}(x)]$, and combines the two GP posteriors at prediction time by weighting them according to the classifier's output. This produces well-calibrated uncertainty estimates within each regime, because GP posteriors are analytically tractable. But the GP inference step has $\\mathcal{O}(n_k^3)$ cost for each regime $k$, where $n_k$ is the number of points assigned to that regime. For the Phantom and Star datasets with $n \\approx 9{,}000$, this means two $\\mathcal{O}(4500^3)$ matrix factorizations per replicate, roughly 600 seconds on 16 CPU cores. The IQN replaces these two cubic-cost GP fits with a single linear-cost neural network trained on all $n$ points simultaneously, reducing the time to 23 seconds on a GPU.\n\nAll of these methods share a common structure: detect the boundary, then fit a model within each regime. The treed GP and Voronoi methods learn the boundary implicitly through their partitioning mechanism. MJGP learns the boundary explicitly (via EM + classifier) and then partitions the data. Aug-IQN learns the boundary explicitly but does *not* partition the data. Instead, it provides the boundary information as an extra feature and trains a single model on all the data. This avoids three problems that plague partition-based methods.\n\nFirst, there is no need to decide how to handle points near the boundary, the classifier's soft probability $\\hat{f}(x) \\approx 0.5$ naturally signals uncertainty, and the IQN can learn to interpolate smoothly through the transition zone. Partition-based methods must make a hard assignment: each point goes to exactly one partition, and points near the boundary may be assigned to the wrong side. Aug-IQN sidesteps this problem entirely by providing the boundary information as a continuous feature.\n\nSecond, there is no loss of statistical efficiency from splitting the data, the IQN sees all $n$ training points, not $n_k$ points per regime. When MJGP partitions 9,000 training points into two regimes, each local GP trains on roughly 4,500 points. The IQN trains on all 9,000. This difference matters most near the boundary, where the local GP has the fewest relevant data points and the IQN has the most informative augmented features.\n\nThird, the single-model approach scales to any number of regimes without a combinatorial explosion of local models, a $K$-regime problem needs one IQN with $K-1$ extra features, not $K$ separate models. With MJGP, adding a third regime means fitting three local GPs (each with its own hyperparameters), managing the assignment of points to regimes, and combining the three posteriors at prediction time. With Aug-IQN, it means adding one more softmax output to the classifier and one more feature to the IQN input.\n\nTreed GPs require MCMC for the tree structure, adding substantial computational overhead and convergence diagnostics. Voronoi methods must optimize the seed-point locations, an NP-hard problem in general that is approximated by heuristics. MJGP inherits the cubic cost of GP inference. Aug-IQN replaces all of this with standard SGD on a neural network, a well-understood optimization problem with reliable convergence properties and GPU acceleration.\n\nThe GBC framework treats every emulation problem as a quantile regression problem, with the only question being what features to provide. For smooth surfaces, the raw inputs $x$ suffice. For jump surfaces, we augment with a boundary indicator $\\hat{f}(x)$. For active learning (@sec-active-learning), we augment with an ensemble disagreement feature. The IQN architecture remains the same in every case, the modular separation of feature engineering from quantile estimation is what makes GBC adaptable to diverse problem structures without requiring specialized architectures for each.\n\n\n## When to Augment: A Practitioner's Checklist {#sec-jumps-when}\n\nThe results across four datasets, Phantom, Star, AMHV, and Michalewicz, distill into a concrete decision procedure.\n\nThe first step is always to plot the marginal response histogram. If the histogram shows two or more clearly separated modes with a visible gap between them, augmentation is likely to help. If the histogram is unimodal, smoothly skewed, or has overlapping modes, augmentation is unlikely to help and may hurt.\n\nThe second step, if the histogram suggests bimodality, is to fit a two-component Gaussian mixture and compute the classification accuracy of the EM labels against the true regime assignments (if known from a pilot study or domain knowledge). If EM accuracy exceeds 95%, the augmentation pipeline will receive clean labels and the downstream classifier will have a strong training signal. If EM accuracy is below 85%, the labels are too noisy to be useful.\n\nThe third step is to train the MLP classifier and check its accuracy. If the classifier achieves $>99\\%$ accuracy on the training set, the augmented feature will provide nearly perfect regime information and Aug-IQN will significantly outperform plain GBC. If the classifier accuracy is below 90%, the augmented feature is noisy and the IQN may not benefit from it. In this case, consider whether a more powerful classifier (deeper network, more epochs, different architecture) might improve accuracy, or whether the boundary geometry is simply too complex for the available training data.\n\nThe fourth step is a sanity check: compare Aug-IQN and plain GBC on a held-out validation set. If Aug-IQN is not clearly better, use plain GBC. The augmentation pipeline adds complexity (EM clustering, classifier training, augmented features), and this complexity should earn its keep by delivering measurably better predictions.\n\nThe entire diagnostic procedure, histogram, GMM fit, classifier training, validation comparison, takes under a minute on a modern workstation and requires no specialized tools beyond scikit-learn and PyTorch, which are already part of the GBC pipeline.\n\nThe Aug-IQN pipeline is deterministic given the random seed. The EM clustering, classifier training, and IQN training all depend on the seed, but the same seed produces the same result every time. This makes the pipeline reproducible and debuggable, if a particular replicate produces poor results, we can re-run it with the same seed and inspect each stage of the pipeline to identify the source of the problem. In our experience, poor results almost always trace back to the classifier: a misclassified region near the boundary that corrupts the IQN's quantile estimates in that neighborhood. The fix is invariably to train the classifier for more epochs or with a wider architecture, not to change anything about the IQN itself.\n\n\n## Exercises {#sec-jumps-exercises}\n\n::: {#exr-em-overlap}\n## EM clustering with overlapping modes\nGenerate a 1D dataset with two regimes where the jump magnitude equals the noise standard deviation: $f_1(x) = 0$, $f_2(x) = \\sigma$, $\\varepsilon \\sim \\mathcal{N}(0, \\sigma^2)$. Fit a two-component Gaussian mixture and measure the clustering accuracy as a function of $\\sigma \\in \\{0.1, 0.5, 1.0, 2.0, 5.0\\}$, using $n = 1{,}000$ points per trial and 20 replicates. At what signal-to-noise ratio does EM clustering begin to fail (accuracy $< 90\\%$)? Plot accuracy vs. signal-to-noise ratio.\n:::\n\n::: {#exr-classifier-ablation}\n## Classifier architecture ablation\nOn the synthetic jump dataset from @sec-jumps-em (jump at $x = 0.5$), train the boundary classifier with four configurations: (a) logistic regression (0 hidden layers), (b) MLP with 1 hidden layer of 64 units, (c) MLP with 2 hidden layers of 128 units, (d) MLP with 3 hidden layers of 256 units. For each configuration, measure classification accuracy and the downstream CRPS when the classifier output is used in Aug-IQN with 3000 IQN epochs. Plot CRPS vs. classifier accuracy. Does the relationship match @tbl-classifier-accuracy?\n:::\n\n::: {#exr-2d-jump}\n## 2D jump function\nConsider a 2D function with a circular jump boundary:\n$$\nf(x_1, x_2) = \\begin{cases} \\sin(\\pi x_1) \\cos(\\pi x_2) & \\text{if } x_1^2 + x_2^2 < 0.5^2, \\\\ 3 + 0.5 x_1 x_2 & \\text{otherwise,} \\end{cases}\n$$\nwith $x_1, x_2 \\in [-1, 1]$ and additive noise $\\varepsilon \\sim \\mathcal{N}(0, 0.1^2)$. Generate $n = 2{,}000$ training points and $n_{\\mathrm{test}} = 500$ test points.\n\n(a) Train a plain IQN with default loss weights and report RMSE and CRPS.\n(b) Train a plain IQN with pinball-dominant loss $(0.10, 0.20, 0.70)$ and compare.\n(c) Implement the full Aug-IQN pipeline (EM + classifier + augmented IQN) and compare.\n(d) Visualize the classifier's learned boundary by plotting $\\hat{f}(x)$ as a heatmap over the input domain.\n:::\n\n::: {#exr-three-regimes}\n## Beyond two regimes\nThe Aug-IQN pipeline assumes a binary jump structure (two regimes). Extend it to handle three regimes:\n$$\nf(x) = \\begin{cases} 0 & \\text{if } x < -0.3, \\\\ 2 & \\text{if } -0.3 \\leq x < 0.4, \\\\ 5 & \\text{if } x \\geq 0.4, \\end{cases}\n$$\nwith $\\varepsilon \\sim \\mathcal{N}(0, 0.2^2)$ and $x \\in [-1, 1]$.\n\n(a) Fit a three-component Gaussian mixture and verify that EM recovers the three modes.\n(b) Replace the binary classifier with a three-class MLP (softmax output). The augmented input becomes $[x, \\hat{p}_0(x), \\hat{p}_1(x)] \\in \\mathbb{R}^3$ (two probability features; $\\hat{p}_2$ is redundant since $\\hat{p}_0 + \\hat{p}_1 + \\hat{p}_2 = 1$).\n(c) Train an IQN on the augmented input and compare to plain IQN. Is the improvement as large as in the two-regime case?\n:::\n\n::: {#exr-ensemble-blur}\n## Ensemble blurring experiment\nGenerate a 1D dataset with $n = 500$ and a jump at $x = 0.5$, using the response function from @sec-jumps-em. Train $K = 5$ IQN models with different random seeds (no augmentation). For each model, record the predicted median across a fine grid $x \\in [0, 1]$. Plot all five median curves overlaid on the same axes, and identify the strip of input space where the models disagree about the boundary location. Then compute the ensemble median (average of the five medians) and compare its CRPS to the best single model's CRPS. Does ensembling help or hurt?\n:::\n\n::: {#exr-boundary-curvature}\n## Boundary curvature and classifier difficulty\nDesign a family of 2D jump boundaries indexed by a frequency parameter $\\omega$:\n$$\n\\text{boundary: } x_2 = A \\sin(\\omega x_1), \\quad \\omega \\in \\{1, 2, 4, 8, 16\\},\n$$\nwhere $A = 0.3$ and $x_1, x_2 \\in [-1, 1]$. For each $\\omega$, generate $n = 3{,}000$ training points with two regimes (above vs. below the sine curve) and responses from two well-separated Gaussian components. Train the MLP classifier and record its accuracy. Plot accuracy vs. $\\omega$. At what frequency does classifier accuracy drop below 95%? How does this translate to downstream Aug-IQN CRPS?\n:::\n\n::: {#exr-soft-augmentation}\n## Hard vs. soft augmentation\nIn the Aug-IQN pipeline, we augment with the classifier's *probability* $\\hat{f}(x) \\in [0, 1]$ (soft augmentation). An alternative is to augment with the classifier's *hard prediction* $\\mathbf{1}[\\hat{f}(x) > 0.5] \\in \\{0, 1\\}$ (hard augmentation).\n\n(a) On the synthetic 1D jump dataset, compare soft and hard augmentation in terms of CRPS.\n(b) Focus on the boundary region $x \\in [0.45, 0.55]$ and compare the two methods' predicted quantile functions.\n(c) Explain intuitively why soft augmentation should be preferred: what information does the probability value $\\hat{f}(x) = 0.7$ provide that the hard label $\\hat{f}(x) = 1$ does not?\n:::\n\n::: {#exr-amhv-diagnostic}\n## AMHV: when not to augment\nGenerate a 1D synthetic dataset that mimics the AMHV setting: a response that transitions smoothly (not sharply) between two regimes:\n$$\nf(x) = 2 + 3 \\cdot \\mathrm{sigmoid}(10(x - 0.5)) + 0.5 x, \\quad x \\in [0, 1],\n$$\nwith $\\varepsilon \\sim \\mathcal{N}(0, 0.3^2)$ and $n = 1{,}000$.\n\n(a) Plot the marginal response histogram and explain why EM clustering will struggle to separate two modes.\n(b) Apply the full Aug-IQN pipeline and compare to plain GBC. Does augmentation help or hurt?\n(c) Formulate a quantitative diagnostic (based on the fitted Gaussian mixture) that predicts whether augmentation will help. Hint: consider the ratio of inter-component distance to within-component standard deviation.\n:::\n\n",
    "supporting": [
      "ch08-jumps_files/figure-pdf"
    ],
    "filters": []
  }
}